chicago-tool-library/circulate

app/controllers/admin/check_outs_controller.rb
app/controllers/admin/member_loan_summaries_controller.rb
app/controllers/admin/members_controller.rb
app/controllers/concerns/member_page.rb
app/controllers/signup/payments_controller.rb
app/helpers/admin_helper.rb
app/helpers/icons_helper.rb
app/javascript/controllers/portal_controller.js
app/javascript/packs/application.js
app/javascript/stylesheets/application.scss
app/models/loan_summary.rb
app/views/admin/adjustments/index.html.erb
app/views/admin/check_outs/_form.html.erb
app/views/admin/loans/_form.html.erb
app/views/admin/member_loan_summaries/index.html.erb
app/views/admin/members/_profile.html.erb
app/views/admin/members/show.html.erb
app/views/admin/memberships/index.html.erb
config/routes.rb
package.json
test/controllers/signup/payments_controller_test.rb
test/system/check_in_check_out_test.rb
test/system/member_verification_test.rb
yarn.lock

This PR adds a much nicer UI for the member page. Items are grouped by due date and photos are displayed.

New member page

---

test/models/loan_test.rb

This should fix the tests that were working yesterday but not today. They are no longer sensitive to the current time.

Fix tests broken by date changing.

---

app/controllers/admin/borrow_policies_controller.rb
app/models/borrow_policy.rb
app/views/admin/borrow_policies/_form.html.erb
db/migrate/20200126220929_add_renewal_limit_to_borrow_policy.rb
db/schema.rb
test/controllers/admin/borrow_policies_controller_test.rb
test/models/loan_test.rb
test/system/borrow_policies_test.rb

Add renewal limit to borrow policy

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/policies/application_policy.rb

Resolves #120 
This adds the pundit gem and a base application policy. 
Needs rules.

add pundit gem and a base application policy

---

app/models/member.rb
test/models/member_test.rb

We'll be figuring out member access privileges through Member instances. This is a minimum viable role implementation to determine that a Member is a member. More roles to come after linking Members to User logins.

add concept of roles to Member

---

app/models/member.rb
app/models/user.rb
db/migrate/20200905185238_add_member_to_user.rb
db/schema.rb
test/models/member_test.rb

Adding member access privileges through Member instances. Adds member, admin, and staff roles.
Co-authored by @robbkidd @amygurski @britth @cflipse @cjilbert504

Add member/user associations and roles to users

---

app/controllers/application_controller.rb
app/models/user.rb
db/seeds.rb

Changes made include updating seed files, teaching Devise to eagerly load member information, and making member information available to controllers and views.
#104

Make current logged-in member info available in session

---

README.md

Add install step to clarify for folks setting up their dev environment

Add install step

---

app/controllers/members_controller.rb
app/helpers/holds_helper.rb
app/models/hold.rb
app/views/members/loans.html.erb
config/routes.rb

Closes https://github.com/rubyforgood/circulate/issues/205

Displays the members items that are on hold

---

app/controllers/admin/appointments_controller.rb
app/helpers/appointments_helper.rb
app/views/admin/appointments/index.html.erb
app/views/layouts/admin.html.erb
config/locales/en.yml
config/routes.rb

This adds appointments link to admin area to list all appointments by date, defaulting to today.
Story [link](https://github.com/rubyforgood/circulate/projects/4)

Create listing page for appointments in admin area

---

app/views/admin/appointments/_checkins.html.erb
app/views/admin/appointments/_checkouts.html.erb
app/views/admin/appointments/index.html.erb
app/views/admin/appointments/show.html.erb

This PR is a left out work from PR #238. 
NOTE: #238 PR implements both items to be checked in and out for specific appointment and enabled user to checkin or checkout single and multiple items.

Add checkins to appointment detail page

---

app/controllers/admin/appointment_holds_controller.rb
app/controllers/admin/appointment_loans_controller.rb
app/views/admin/appointments/_checkins.html.erb
app/views/admin/appointments/_checkouts.html.erb
app/views/admin/appointments/show.html.erb
config/routes.rb

This PR adds remove button for each item so that the related appointment holds and loans can be removed.

Add and implement remove button for checkin and checkout items

---

Gemfile
Gemfile.lock
app/controllers/appointments_controller.rb
app/lib/open_days.rb
app/models/appointment.rb
app/models/hold.rb
app/views/appointments/new.html.erb
app/views/members/loans.html.erb
config/initializers/chronic.rb
config/routes.rb
test/lib/open_days_test.rb

Closes https://github.com/rubyforgood/circulate/issues/204.

Members can create a new appointment

---

app/controllers/admin/appointments_controller.rb
app/helpers/appointments_helper.rb
app/models/appointment.rb
app/views/admin/appointments/index.html.erb
app/views/admin/appointments/show.html.erb
config/routes.rb

This PR adds a cancel button to delete appointment and the associated records from the database.

Implement cancel appointment functionality

---

app/views/layouts/_user.html.erb

Should be included in the existing drop down at the top of the page.

#229 Add Navigation Links for "My Loans / My Holds" and "Schedule An Appointment"

---

app/javascript/stylesheets/globals.scss
app/javascript/stylesheets/mixins.scss
app/views/admin/dev/styles.html.erb
app/views/member_profiles/show.html.erb

This PR gets rid of the need to add a class to the copy for the button. By targeting the `a` within the `primary-btn` or `secondary-btn` class, it correctly styles the words.

Updated code of button to be more efficient

---

app/controllers/admin/appointment_checkouts_controller.rb
app/controllers/admin/appointment_holds_controller.rb
app/controllers/admin/appointments_controller.rb
app/models/item.rb
app/views/admin/appointments/_checkouts.html.erb
app/views/admin/appointments/show.html.erb
config/routes.rb

This adds a form to appointment page to add a new item to it.

Implement item addition to appointment

---

config/database.yml

This PR allow you setup password in test and development environment in .env file.

added POSTGRES_PASSWORD env variable

---

app/controllers/admin/appointments_controller.rb
app/views/admin/appointments/index.html.erb

This PR add a custom date display on scheduled Appointments page (#270)

Custom date display

---

app/views/layouts/application.html.erb

Swapped around the nav bar links in the layout requested.

Rearranged nav bar links

---

app/views/layouts/application.html.erb

amended mobile nav links in member pulldown to match desktop

---

app/controllers/admin/members_controller.rb
app/helpers/members_helper.rb
app/javascript/stylesheets/application.scss
app/models/member.rb
app/views/admin/members/_members.html.erb

[Librarian] Show loans and holds stats on members index [#154]

---

yarn.lock

Closes #130
Ran `yarn upgrade` and had all system tests pasing locally. A brief manual test also revealed no issues.
It may make sense to enable [Dependabot](https://dependabot.com/) to have a bot PRs for these sort of changes.

Update JS packages

---

app/views/members/loans.html.erb

This PR have a Goal solve the problem in Member Hold list.
When member has no item on hold, show message: 'You have no items on hold'
The behavior was replicated to Loan, in the same screen.
card: https://github.com/rubyforgood/circulate/issues/288

added message when no have items on hold and loan

---

app/controllers/admin/bulk_renewals_controller.rb
app/views/admin/members/show.html.erb
config/routes.rb
db/seeds.rb
test/controllers/admin/bulk_renewals_controller_test.rb

Closes #156 
This PR is a good first iteration on bulk loan renewal in the admin panel.
It also includes some updates to seed data for ease of testing this functionality locally.

Adds Renew All Button

---

app/views/members/loans.html.erb

This PR is add button close to Checked out items table.
card: https://github.com/rubyforgood/circulate/issues/295

295-added Schedule a Pick up button in Checked-out Items

---

config/application.rb
config/environments/production.rb
config/initializers/staging_access.rb

This adds the ability to view email previews on staging and reorganizes some configuration accordingly.

Enable mailer previews in production if an env var is set.

---

app/views/layouts/admin.html.erb

This PR has a goal to add Appointment link in admin mobile version.
card: https://github.com/rubyforgood/circulate/issues/315

315-added appointments link to mobile version

---

app/controllers/admin/members/holds_controller.rb
app/views/admin/members/holds/index.html.erb
test/controllers/admin/members/holds_controller_test.rb

Addresses the issue https://github.com/rubyforgood/circulate/issues/75.
@jim I'm not sure if there is a better way to do this. Open to suggestions on code improvement.

Showing member's place in line on the members hold  screen in the admin member holds view

---

app/controllers/appointments_controller.rb
app/controllers/member_holds_controller.rb
app/controllers/member_profiles/passwords_controller.rb
app/controllers/member_profiles_controller.rb
app/controllers/members_controller.rb

I have added the authentication to all controllers that require them as far I know. Please let me know if I missed any controllers that required authentication.

Fixed internal error when navigating to pages that require login. Issue#316

---

app/lib/spectre_form_builder.rb
app/views/admin/appointments/_checkouts.html.erb

This PR has Goal to improve Appointments View like describe in card: https://github.com/rubyforgood/circulate/issues/309

added optional label for form builder

---

app/views/account/appointments/index.html.erb

Hey,
Just added a div which will show a message telling the user that there are no scheduled appointments when the variable `@appointments` is blank
#342

Fail more gracefully when no appointments are present

---

app/views/admin/holds/index.html.erb

Branch to add item number to Holds page to resolve issue #345 
I've had some difficulty running the project on my local machine so am marking this as a draft pull request, if you can please double check it for me first?

added number to holds page #issue 345

---

app/javascript/stylesheets/admin.scss
app/javascript/stylesheets/application.scss
app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb

Resolves the issue #353, I've added the footers in all the member-facing pages. I've added too in home and login, in my opinion it's always good to show the footer with contact information.

Added footer to all member-facing pages

---

app/controllers/admin/members_controller.rb
app/controllers/admin/notes_controller.rb
app/javascript/stylesheets/application.scss
app/models/member.rb
app/views/admin/members/_form.html.erb
app/views/admin/members/_member.json.jbuilder
app/views/admin/members/_member_details.html.erb
app/views/admin/members/show.html.erb
config/routes.rb
db/migrate/20201024225228_rename_member_notes_to_bio.rb
db/schema.rb
test/controllers/admin/members_controller_test.rb
test/factories/members.rb
test/models/member_test.rb

Closes https://github.com/rubyforgood/circulate/issues/155

Librarian Member Notes 

---

app/helpers/loans_helper.rb

minor formatting changes to item return date on My Loans
Not important! Just tweaks to make it read better.

formatted appointment date for item return

---

app/helpers/holds_helper.rb

minor formatting changes to item pick-up date on My Loans
Not important! Just tweaks to make it read better.

formatted date for pick-up

---

app/javascript/stylesheets/application.scss
app/views/items/show.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/application.html.erb

Changed footer specs to fix issue #374
Fixes the issue #374.
After
* Choose for a fixed footer.

Fixed footer display on Items page.

---

test/system/member_profile_test.rb

_Describe the changes that you've made to the application in this PR.
_Make a case for merging this work. This might include linking to a relevant issue.

Fix broken system tests.

---

app/controllers/admin/appointments_controller.rb

This is a fix to update item count after checking out item, like described in card: https://github.com/rubyforgood/circulate/issues/379

379-fixed Items to be checked-out

---

app/views/gift_purchaser_mailer/confirmation.mjml
app/views/gift_purchaser_mailer/confirmation.text.erb
app/views/member_mailer/_reminder.erb
app/views/member_mailer/_summaries.erb
app/views/member_mailer/membership_reminder.mjml
app/views/member_mailer/summary.mjml
app/views/member_mailer/summary.text.erb
app/views/member_mailer/welcome_message.mjml
app/views/signup/confirmations/_instructions.html.erb

Updates the emails to reflect that members can login to the site now.
Closes #352.

Update email templates.

---

app/controllers/account/home_controller.rb
app/controllers/account/loans_controller.rb
app/views/layouts/_user.html.erb
test/system/user_signup_test.rb

This is a small collection of fixes for the member UI that I discovered today while testing it out in production.

Small UI fixes

---

app/views/gift_purchaser_mailer/confirmation.mjml
app/views/gift_purchaser_mailer/confirmation.text.erb
app/views/member_mailer/_reminder.erb
app/views/member_mailer/_summaries.erb
app/views/member_mailer/membership_reminder.mjml
app/views/member_mailer/summary.mjml
app/views/member_mailer/summary.text.erb
app/views/member_mailer/welcome_message.mjml
app/views/signup/confirmations/_instructions.html.erb

Reverts rubyforgood/circulate#386
We're going to re-deploy these in a few days/week when we're ready to communicate with members how to log in.

Revert "Update email templates."

---

app/javascript/stylesheets/application.scss
app/javascript/stylesheets/partials/_users_sign_in.scss
app/views/devise/sessions/new.html.erb

This PR updates the member login page to explain its purpose.

Revise member login page

---

app/views/gift_purchaser_mailer/confirmation.mjml
app/views/gift_purchaser_mailer/confirmation.text.erb
app/views/member_mailer/_reminder.erb
app/views/member_mailer/_summaries.erb
app/views/member_mailer/membership_reminder.mjml
app/views/member_mailer/summary.mjml
app/views/member_mailer/summary.text.erb
app/views/member_mailer/welcome_message.mjml
app/views/signup/confirmations/_instructions.html.erb

Reverts rubyforgood/circulate#391
We're ready for the new emails to be live now 😄

Revert "Revert "Update email templates.""

---

app/controllers/admin/appointments_controller.rb
app/javascript/stylesheets/partials/_admin_appointments.scss
app/models/appointment.rb
app/views/admin/appointments/index.html.erb

This PR makes some usability improvements to the admin appointments screen to improve readability.

Sort the appointments and adjust styling and display.

---

app/controllers/admin/reports/memberships_controller.rb
app/views/admin/reports/memberships/index.html.erb
app/views/layouts/admin.html.erb
config/initializers/pagy.rb
config/routes.rb

Adds a new report that shows information about memberships. It can be viewed in the app or exported to CSV.
Our development team needs to have this information as a part of planning finances and renewal processes.
* I created an `Admin::Reports` module for this controller. I think it makes sense to migrate the other report controllers into it as time goes on to keep things organized.

Add memberships report.

---

app/views/volunteer/shifts/index.html.erb

This addresses an issue where the attendees were being counted by day and not shift. This was a problem on Saturdays, when we have more than one shift.

Fix bugs in shift attendee count.

---

app/views/items/index.html.erb

Don't hide category list on mobile.

---

app/views/admin/appointments/show.html.erb
app/views/admin/members/_membership_status.html.erb
bin/reset
db/seeds.rb
lib/tasks/db.rake

Some issues were found in the new membership renewal stuff. This should fix them.

Fix membership renewal bugs

---

app/models/membership.rb
app/views/member_mailer/membership_renewal_reminder.text.erb
app/views/member_mailer/renewal_message.text.erb
lib/tasks/email.rake

* Adds text version of membership renewal reminder email
* Sends emails in the rake task

Fix membership renewal emails

---

.env.example

PR #445 change postgres credentials variables , and its necessary to update these on .env.example

fix database environment variables in dotenv.example

---

app/helpers/items_helper.rb
app/views/items/_details.html.erb
test/helpers/items_helper_test.rb

Don't show that A tools are on hold or checked out in the item inventory

---

app/helpers/items_helper.rb
app/views/items/_details.html.erb

#482 
- Add link for categories in item detail page to filter with the corresponding category
- For user to be more convenient browsing the inventory

add filter link for categories on item detail page

---

app/controllers/account/holds_controller.rb
app/controllers/account/home_controller.rb
app/controllers/admin/appointment_holds_controller.rb
app/controllers/admin/item_holds_controller.rb
app/controllers/admin/members/hold_loans_controller.rb
app/controllers/admin/members/holds_controller.rb
app/controllers/items_controller.rb
app/helpers/items_helper.rb
app/models/hold.rb
app/views/account/holds/index.html.erb
app/views/account/home/index.html.erb
app/views/admin/renewal_requests/index.html.erb
config/routes.rb
test/system/holds_test.rb

Some parts of the app didn't get updated when we moved to having holds that became inactive. This PR addresses many of these.

Update some associations to limit them to active holds

---

app/views/admin/members/_member_details.html.erb

Adds links between the member and appointment pages.

Add links to member details panel

---

app/helpers/items_helper.rb
app/models/hold.rb
app/models/item.rb
app/views/items/show.html.erb
test/helpers/items_helper_test.rb
test/models/hold_test.rb
test/system/holds_test.rb

This prevents users from putting items on hold that are in maintenance.

Prevent maintenance holds

---

app/controllers/admin/renewal_requests_controller.rb
app/mailers/member_mailer.rb
app/views/member_mailer/renewal_request_updated.mjml
app/views/member_mailer/renewal_request_updated.text.erb
test/mailers/member_mailer_test.rb
test/mailers/previews/member_mailer_preview.rb
test/system/admin/renewal_requests_test.rb

This PR adds emails to members when their renewal requests are responded to by staff.

Renewal request notifications

---

app/controllers/admin/appointment_completions_controller.rb
app/controllers/concerns/portal_rendering.rb
app/helpers/admin_helper.rb
app/helpers/application_helper.rb
app/javascript/controllers/portal_controller.js
app/javascript/stylesheets/partials/_admin_appointments.scss
app/models/appointment.rb
app/views/admin/appointments/_appointment.html.erb
app/views/admin/appointments/index.html.erb
app/views/admin/appointments/show.html.erb
app/views/layouts/_portal_table_row.html.erb
config/routes.rb
db/migrate/20210519212401_add_completed_at_to_appointments.rb
db/schema.rb
test/system/admin/appointments_test.rb

Implements a version of the requirements for #453

Allow staff to mark appointments as complete.

---

.gitignore
app/controllers/account/appointments_controller.rb
app/models/appointment.rb
app/views/account/appointments/index.html.erb
test/models/appointment_test.rb
test/system/appointments_test.rb

When members make an appointment for the same time as an existing appointment, the system merges them together.

Duplicate appointments

---

app/views/admin/item_holds/index.html.erb

Show how long until a hold expires

---

app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb
app/views/layouts/steps.html.erb

We're trying out weglot to see if having it on the public pages is helpful.

Replace plausible with Weglot

---

app/controllers/admin/base_controller.rb
app/javascript/stylesheets/admin.scss
app/views/layouts/admin.html.erb

* Shows a banner when there are renewal requests that need to be responded to.

Show banner when there are waiting renewal requests.

---

app/controllers/account/appointments_controller.rb
app/views/account/appointments/index.html.erb
app/views/home/index.html.erb
test/controllers/account/appointments_controller_test.rb

Fixes an issue where an appointment disappears as soon as its start time has passed.

Appointments show all day

---

app/controllers/admin/items_controller.rb
app/views/admin/items/index.html.erb

This PR brings the collapsible categories to the admin UI.

Bring collapsible categories to the admin UI.

---

app/controllers/admin/notes_controller.rb
app/javascript/stylesheets/admin.scss
app/javascript/stylesheets/application.scss
app/models/note.rb
app/views/admin/members/_member_details.html.erb
app/views/admin/members/_profile.html.erb
app/views/admin/members/show.html.erb
app/views/admin/notes/new.html.erb

Displays a member's notes at the top of their profile
#681

Display member notes at the top of their profiles

---

test/system/admin/members_test.rb

Add system test for member page in admin view
Follow-up PR for this: https://github.com/rubyforgood/circulate/pull/649#pullrequestreview-761509541

Add system test for member page of admin view

---

README.md

Updated features list, office hours status, and some Project Board management tips.
Minor text updates for RFG 2021.

Updates to features and intro paragraph

---

app/views/admin/members/memberships/new.html.erb

We wanted the explanation of pay-what-you-can for the CTL to be more descriptive, so we updated the copy.
Resolves #696.
Unable to upload images to github at this time due to connectivity :joy:
- [ x ] I am interested in feedback but don't need to make the changes myself.

Elaborate on CTL's pay-what-you-can approach in payment form

---

app/controllers/admin/members_controller.rb

Fixes bug where an admin could not edit a member's bio
See #651
N/A
N/A
- [X ] I have the time and interest to make additional changes to this PR based on feedback.

add bio to permitted admin member_params

---

app/views/account/appointments/_form.html.erb
test/system/appointments_test.rb

Updates text in the optional notes 
See issue #676 
N/A

676 update notes label

---

lib/tasks/export.rake

This PR removes two similar member export features and replaces them with a single one that is currently in use.
We sometimes need to export member information into other systems.

feat: update member export for use with other tools

---

README.md

_Describe the changes that you've made to the application in this PR.
_Make a case for merging this work. This might include linking to a relevant issue.

[ci skip] Fix typographical errors in `README`

---

app/views/account/members/_form.html.erb
app/views/admin/members/_form.html.erb

- Fix https://github.com/rubyforgood/circulate/issues/650
_Make a case for merging this work. This might include linking to a relevant issue.

Remove local variable `show_password_inputs`

---

app/forms/extend_holds_form.rb

This fixes a test that is breaking the main branck.

Use 30 days as the limit for extending holds

---

app/javascript/stylesheets/homepage.scss
app/views/homepage/index.html.erb

We have had some styles that are specific to the software homepage leak out and affect other parts of the app. This PR namespaces them to a top-level `.homepage` class to avoid this.
We don't want styles that aren't intended to be global to affect the entire app!
I noticed this because all of the inputs in the app have been using the wrong font recently:
This issue is fixed by this PR, and we have sans-serif fonts in our inputs again.

Namespace homepage styles.

---

lib/tasks/export.rake

This new export format makes it easier to import the data into Neon CRM.

Update format of members export to ease import into neon.

---

.github/workflows/ci.yml

This PR specified versions of the following an action to prevent CI failures
- nanasess/setup-chromedriver@v1
#1017 
N/A

Specify setup-chromedriver@v1

---

app/models/hold.rb
lib/tasks/production.rake
test/system/admin/consumables_test.rb

This PR fixes an issue where consumable items couldn't be checked out from the appointment page when they had a quantity of 1.

Appointment consumable bug fix

---

app/models/categorization.rb

This restores some callbacks that went missing in a recent refactor.

Restore callbacks to refresh CategoryNodes

---

app/controllers/admin/renewals_controller.rb

This PR gracefully handles when renewing an item fails.

Show error when a renewal can't be made.

---

app/mailers/member_mailer.rb
app/views/member_mailer/membership_renewal_reminder.mjml

Revises the email copy to make the renewal emails make sense in the library's third year.

Update member renewal copy.

---

app/controllers/admin/dashboard_controller.rb
app/views/admin/dashboard/index.html.erb

This adds two new numbers on the admin dashboard, "Verified Members" and "New Verified Members"
Fixes #1046 
I didn't link the right branch last time, so this is my second attempt at this pull request.

Adding Verified Members Data

---

app/controllers/admin/items_controller.rb
app/models/item.rb
app/views/admin/items/_form.html.erb
db/migrate/20220902013538_add_purchase_price_and_purchase_link_to_item.rb
db/schema.rb
lib/tasks/import.rake

This adds a few columns to the `items` table to store some additional metadata that folks have collected.

Add item value

---

.github/workflows/ci.yml
test/application_system_test_case.rb
test/system/admin/gift_memberships_test.rb
test/system/admin/items_test.rb
test/system/appointments_test.rb
test/system/holds_test.rb
test/system/membership_renewal_test.rb
test/system/user_signup_test.rb

Makes it so CI is passing again.

Fix system tests in CI

---

app/controllers/admin/settings/exports_controller.rb
app/lib/item_exporter.rb
app/views/admin/settings/exports/index.html.erb
app/views/layouts/admin.html.erb
config/routes.rb
lib/tasks/export.rake
test/lib/item_exporter_test.rb

Adds a button to the admin UI to export items.

Add item exporting to admin

---

.github/workflows/ci.yml
Gemfile
Gemfile.lock
app/controllers/admin/settings/exports_controller.rb
app/lib/member_exporter.rb
app/models/member.rb
app/models/membership.rb
app/views/admin/settings/exports/index.html.erb
app/views/layouts/admin.html.erb
config/routes.rb
test/application_system_test_case.rb
test/lib/member_exporter_test.rb

Adds a member and membership export to the admin UI.

Add member export and fix system tests

---

.env
app/helpers/items_helper.rb
config/application.rb
test/helpers/items_helper_test.rb

Reverts chicago-tool-library/circulate#1164
See https://github.com/chicago-tool-library/circulate/pull/1164#issuecomment-1786219584 for background.

Revert "Remove ImageKit"

---

app/views/layouts/mailer.html.mjml
app/views/layouts/mailer.text.erb
app/views/member_mailer/_donation.html.erb

Adds a notice to the mailer layout that prompts recipients to donate to the tool library. Fixes #1195.
We're missing an opportunity to engage make it as easy as possible to support the tool library.
Before:
After:
* I also tweaked the styles of the various banners to remove the heavy outlines. With 3 banners it seemed really distracting to me.

Add donation info to transactional emails.

---

README.md

Adds some info to the README about local Heroku setup. I also updated the list of Buildpacks since it was out of date.

Add Heroku info and update list of buildpacks

---

Gemfile.lock
package.json
yarn.lock

Updating ruby and JS sides together for a safer upgrade. Closes #1319
Keeping up with the joneses 😄

Update turbo to v8

---

app/controllers/admin/appointment_completions_controller.rb
test/controllers/admin/appointment_completions_controller_test.rb

Fixes #1428 
The appointments page should render correctly!

Honor feature flag in turbostream appointment rendering

---

app/helpers/items_helper.rb

Convert rotation to integer when fetching variant

---

app/views/member_mailer/_donation.html.erb

Changes the donation link to a new one provided by @tessavierk

Update donation link

---

app/views/member_mailer/_donation.html.erb

Reverts chicago-tool-library/circulate#1511

Revert "Update donation link"

---

public/robots.txt

Resolves #1569 
Removes source of potential noise from logs and traffic.

Block all bots in robots.txt

---

lib/tasks/devdata.rake

Prevents us from copying the fixture image once per ~400 items loaded during devdata
Part of work on #1598 
* I was also able to rework the AnalyzeJob workaround in a way that should prevent AnalyzeJobs from flying around in the dev env.
* As mentioned in the comments, this means the fixture image will get rotated everywhere if it's rotated. I think this is a reasonable tradeoff for how much repeated churn this saves.

devdata: Reuse image blobs to save space and maybe a little time

---

app/assets/stylesheets/styles.scss

I replaced a CSS class that was removed as part of d872996
It resolves #1839
My editor autocorrected a bunch of whitespace on save so I need to remove that right after I open this PR.

fixes #1839 - Categories table is broken/missing styles

---

.envrc
flake.lock
flake.nix

Spruces up the nix development environment that I use. The required change is `nix flake update` so the latest ruby version is picked up, the other changes (direnv-nix update, flake.nix formatting) are for good measure.
Only important for people using Nix dev setup, which at this point is just me. :)

Update Nix setup

---

app/views/signup/home/index.html.erb

We are having orgs go through a Google form now, so let's just take them directly there.

Update organization signup link
