- app/models/member.rb
- test/models/member_test.rb
If a Postal Code has been entered, validate that it is a Chicago postal
code defined as either 60707, 60827, or any 606 code. This will need
refactored for other areas once multi-tenancy decisions have been made.
fixes #73
> Validate Chicago postal code

- db/migrate/20200420175849_rename_tags_to_categories.rb
- db/schema.rb
When running the `db:migrate` task from beginning to end, the migration
breaks on `20200420175849_rename_tags_to_categories.rb` with an error
that there is no `tags` relation. Digging into this a bit more, it looks
like this migration exists to counteract the from commit 96d3342 which
set out to rename categories to tags. That work was subsequently
reverted in commit 897d43a which deleted that migration. This remaining
artifact is to rename tags back to categories but there is no tag table
as the code was never long lived in the baseline from what I can tell.
After deleting this migration and re-running the rake task, there appear
to be no functional changes to any of the content in the `schema.rb`.
The few changes that do appear are adding trailing commas and re-arrange
the custom views, …
> Remove broken migration with missing tags relation

- app/models/member.rb
- app/models/user.rb
- db/migrate/20200906142639_add_member_to_role_enum.rb
- db/migrate/20200906142955_change_default_role_on_user.rb
- db/schema.rb
- test/models/member_test.rb
Fixes #135 
* adds a test for "member" being default
* updates the enums that define the list of known roles to include "member"
* `member.roles` simplified to delegate to `member.user.roles`
> make a new member's default role be "member"

- app/helpers/admin_helper.rb
- test/system/items_test.rb
Using `find` throws an error on an item's edit history page when the category has been deleted. Updates the query to use `where` instead. If the number of categories found is less than the number of keys, add the string `deleted category` to signify that there was also a now missing value associated with the item. Adds a test to exercise this behavior.
Issue #41
ruby -I ./test test/system/items_test.rb output:
Finished in 10.779663s, 0.6494 runs/s, 1.4843 assertions/s.
7 runs, 16 assertions, 0 failures, 0 errors, 1 skips
> Swap find for where to grab category names

- app/models/item.rb
- test/models/item_test.rb
When an item has no categories (whether on creation or if the categories are all cleared), the audit history will not include an entry when a category is subsequently added. Two changes must be made before it is saved. This is because there is a check for presence of cached category ids before initiating the audit addition. This PR updates the logic to ensure that an entry is created anytime the new category ids do not match the cached category ids.
Co-authored with @johnksawers 
Finished in 5.790894s, 29.5291 runs/s, 96.8762 assertions/s.
171 runs, 561 assertions, 0 failures, 0 errors, 2 skips
> Ensure that single category changees are saved in audit history

- README.md
The old CircleCI badge was no longer working.  This pull request fixes it.
> Updated the CircleCI badge

- app/models/appointment.rb
- app/models/appointment_hold.rb
- app/models/member.rb
- db/migrate/20200923151427_create_appointments.rb
- db/migrate/20200923152956_create_appointment_holds.rb
- db/schema.rb
- test/factories/appointment_holds.rb
- test/factories/appointments.rb
- test/models/appointment_hold_test.rb
- test/models/appointment_test.rb
This adds appointment and appointment holds tables and models with all the relationships.
We came up with the names for models and we can discuss it here if we want a different naming.
We currently have `appointment_holds` joint table to store multiple holds for an appointment. 
In conversation with Greg, we thought it would be ok for us to use this joint table for pickup and returns. We would need to check for `loan_id` on the hold and if nil, we assume it's a hold without loan yet, otherwise, we assume it's a loan and it's being returned.
All of these are open to discussion.
Story [link](https://github.com/rubyforgood/circulate/issues/227)
> Create table, model for appointment and appointment holds

- config/puma.rb
When workers are specified, Puma will run in a clustered mode. Worker
processes will be killed if they do not report back to the parent
process that manages the cluster. This makes using debugging tools very
frustrating and less than productive. When the worker processes is
killed the debugging session is broken, and the standard in is
closed.
To address this issue, only specify a worker configuration when the
environment is not development.
> Fix puma config to work with debugging

- app/javascript/stylesheets/globals.scss
- app/views/admin/dev/styles.html.erb
Renamed custom link button class to avoid naming conflict with existing `.btn-link` class.
> Fix btn-link naming conflict

- app/views/layouts/admin.html.erb
- app/views/layouts/application.html.erb
If a Member is a librarian, display a link to the admin pages in the general navbar. Possibly to the left of the member name? E.g., "Go to Admin display," though there's probably a shorter way of saying it. Maybe "Admin" with an arrow or other graphic?
Possibly also do similar on the admin pages, linking to the Member pages? (E.g., "Go to Member display," or something shorter.)
Closes https://github.com/rubyforgood/circulate/issues/182
> #182 Add a link on the non-admin navbar (including on Member pages) for librarians to get to the admin pages if logged in.

- app/views/members/loans.html.erb
- test/models/membership_test.rb
- test/system/member_checked_out_items_test.rb
Fix item link from `/members/loans` checkout table such that clicking
on it will take the member to that item's overview page.
Issue #253
`rails test`
208 runs, 624 assertions, 0 failures, 0 errors, 2 skips
`rails test test/system/member_checked_out_items_test.rb`
1 runs, 3 assertions, 0 failures, 0 errors, 0 skips
(getting a couple of errors for other system tests, but appear unrelated)
> Fix item link on loans page

- app/controllers/admin/items_controller.rb
- app/helpers/items_helper.rb
- app/models/item.rb
- app/views/admin/items/_form.html.erb
- app/views/admin/items/_profile.html.erb
- app/views/items/_details.html.erb
- db/migrate/20201002020141_add_power_source_to_items.rb
- db/schema.rb
- test/controllers/admin/items_controller_test.rb
- test/factories/items.rb
- test/system/items_test.rb
Resolves #152
Add `power_source` to `Item`.
> Add power source field to items

- app/lib/spectre_form_builder.rb
- test/system/gift_memberships_test.rb
- test/system/items_test.rb
It's possible to click buttons multiple times and accidentally
create duplicate items. This PR updates the submit method to
utilize the data-disable HTML attribute. This will grey out the
button on submit to prevent unintentional multi clicks. Adds a
couple of tests to ensure that duplicate items aren't created
when double clicking (specifically for new items and gift
memberships). These tests should fail on current development but
pass on this branch.
Issue #157
rails test
208 runs, 624 assertions, 0 failures, 0 errors, 2 skips
rails test:system
58 runs, 249 assertions, 2 failures, 0 errors, 4 skips
(seemingly unrelated: test/system/holds/holds_test.rb:21 and test/system/holds/holds_test.rb:70)
> Disable button on submission

- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
Fixes https://github.com/rubyforgood/circulate/issues/219
- Remove admin login button since it leads to the same page anyway
- Add a check when user is logged in, it won't show the button to register.
> 219 unify login

- app/controllers/admin/base_controller.rb
- test/controllers/admin/borrow_policies_controller_test.rb
- test/controllers/admin/categories_controller_test.rb
- test/controllers/admin/dashboard_controller_test.rb
- test/controllers/admin/documents_controller_test.rb
- test/controllers/admin/gift_memberships_controller_test.rb
- test/controllers/admin/hold_loans_controller_test.rb
- test/controllers/admin/items_controller_test.rb
- test/controllers/admin/loan_summaries_controller_test.rb
- test/controllers/admin/loans_controller_test.rb
- test/controllers/admin/member_requests_controller_test.rb
- test/controllers/admin/members/requests_controller_test.rb
- test/controllers/admin/members_controller_test.rb
- test/controllers/admin/memberships_controller_test.rb
- test/controllers/admin/monthly_activities_controller_test.rb
- test/controllers/admin/monthly_adjustments_controller_test.rb
- test/controllers/admin/potential_volunteers_controller_test.rb
- test/controllers/admin/renewals_controller_test.rb
- test/controllers/admin/searches_controller_test.rb
- test/controllers/admin/ui_controller_test.rb
- test/controllers/admin/users_controller_test.rb
- test/controllers/admin/verifications_controller_test.rb
- test/fixtures/users.yml
Fixes https://github.com/rubyforgood/circulate/issues/218
1. Implement `require_admin` check at `app/controllers/admin/base_controller.rb`
2. When failed, it will redirect to root_url (tentative)
3. `test/fixtures/users.yml` the admin user is now an actual admin
4. Make admin tests actually use the admin-user.
> fix admin fixture, use admin user, fix redirect

- db/seeds.rb
After pulling latest development and attempting to login with the
admin@chicagotoollibrary.org user, I was unable to view the admin
dashboard. After checking in my console, I saw that this user did
not have the role of admin. This PR updates the seed to set its
role to admin.
(I could definitely be missing something, but this is the user I
had previously been logging in as when testing admin functionality!)
system tests:
58 runs, 278 assertions, 0 failures, 0 errors, 4 skips
unit tests:
208 runs, 624 assertions, 0 failures, 0 errors, 2 skips
> Set role for admin user seed to admin

- app/controllers/concerns/calendaring.rb
- test/system/holds/holds_test.rb
In https://github.com/rubyforgood/circulate/commit/826da0b35259a506811a67616e4b7540332296ee, it looks like `Result#errors` was renamed `Result#error`. One 
spot that appears to have been missed is in `calendaring.rb`. Locally, I was
getting an error `Undefined method errors for <result...>` when trying
to access the volunteer shifts report. Updating to `error` allowed the
page to load and revealed a permissions error. This PR updates these
remaining calls to `.errors`. Potentially it might make sense to further
update the error text that is flashed, but I did not make that update as
yet.
before
after
(I also updated two unrelated system tests in this commit, as without
the `wait` they occasionally fail for me locally. Can back that out if 
desired though!)
unit tests:
208 runs, 624 …
> Update errors -> error in calendaring module

- app/controllers/admin/items_without_image_controller.rb
- app/models/item.rb
- app/views/admin/items_without_image/index.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- test/controllers/admin/items_without_image_controller_test.rb
- test/models/item_test.rb
This feature was necessary to list all product without photos.
card: https://github.com/rubyforgood/circulate/issues/153
> added report that list all items without photo

- Gemfile
- Gemfile.lock
- README.md
- test/application_system_test_case.rb
This gem will automatically install webdrives needed to run Selenium
tests.
Since the test setup only uses `chromedriver`, we only `require` that in
our `application_system_test_case` setup.
When getting set up and creating #291, I ran into system test failures because
I didn't have chromedriver installed. I thought this gem could help make it easier 
for other developers to get set up to contribute more quickly.
> Add `webdrivers` gem to automatically install `chromedriver`

- README.md
- bin/setup
Running `bin/setup` on a new project was failing with the following
error:
```
error Couldn't find a binary named "mjml"
rails aborted!
Couldn't find the MJML 4. binary. Have you run $ yarn add mjml?
```
This was failing when attempting to create the database. I believe this
is related to bootsnap loading the environment and the `mjml-rails` app
expecting the `mjml` binary to exist.
By running `yarn` first the `mjml` npm package will be installed and the
binary will be available, enabling `bin/setup` to complete
successfully.
> Update setup script to run yarn

- app/helpers/items_helper.rb
- app/javascript/stylesheets/application.scss
This PR only updates styling to make labels more readable. It doesn't deal with the suggested dropdown, as the details of what that would look like were a bit hazy.
To look at implementing a dropdown menu a bit of design is needed, I think. At the moment, categories can allow any number of nested sub-categories. For that reason, we'd need to consider where we want the caret/arrow icon to be: only on the first parent or on all nested categories that in their turn have subcategories?
For the moment, I think a simple implementation like the one in this PR is cleaner and more readable.
> update category nav helper and styles to make labels more readable

- app/controllers/appointments_controller.rb
- app/javascript/stylesheets/application.scss
- app/models/appointment.rb
- app/views/appointments/_form.html.erb
- test/models/appointment_hold_test.rb
- test/models/appointment_test.rb
Fixes #276 
Please find the screenshots with the error messages displayed.
**Screen 1**: Appointment Form
**Screen 2**: Form is submitted without selecting item and date. Shows respective error messages
**Screen 3**: Form is submitted by selecting item and not selecting date. Shows error message only for date.
**Screen 4**: Form is submitted by selecting date and not selecting item. Shows error message only for item.
**Screen 5**: Form is submitted by selecting date and selecting item. Appointment is saved successfully.
> added form validation for appointment creation

- app/views/admin/appointments/index.html.erb
- test/system/admin/appointments_test.rb
When viewing an appointment there are now links that render for members names and items that will take you to the librarian view.
Fixes #314
> Add links to member and item pages

- app/controllers/member_profiles/passwords_controller.rb
- app/views/member_profiles/passwords/edit.html.erb
- test/controllers/member_profiles/password_controller_test.rb
When members edit their password, they are now required to enter their current password.
Adds current password field, adjusts field labels for clarity (e.g. default Password -> New Password), and updates the password controller tests accordingly.
Linked to #167
> Add password confirmation when user edits password

- test/factories/members.rb
- test/system/member_verification_test.rb
There are _Checking for expected text of nil is confusing and/or pointless since it will always match. Please specify a string or regexp instead._ during the system tests. The problem is the member's number is nil in those tests.
add :number to verified_member factory
do @member.reload after page changed so that the controller has done its action
> Prevent the printed warning messages in system tests

- app/models/member.rb
***Why?***
I am not sure if this is possible on production or if this is a glitch on my local dev database.
I updated my pronouns from `she/her` to `he/him` on my localhost and noticed an extra comma after `he/him`
***How?***
- Added a `.reject` to remove the empty values from the pronouns array
***Screenshots***
> Remove extra comma from pronouns

- app/views/account/members/_form.html.erb
- app/views/admin/members/_fields.html.erb
- app/views/admin/members/_form.html.erb
- app/views/signup/members/new.html.erb
Hey,
Added an additional parameter to the partial `admin/members/_fields.html.erb` which is rendered to show the form fields
The additional argument is used to filter the password inputs from the form
This parameter is set as `false` in case of Member profile edit page and true elsewhere
#347
> Hide Password Inputs on Member Profile Edit Page

- app/helpers/holds_helper.rb
- app/models/hold.rb
- app/views/account/home/index.html.erb
Hide the "remove" link next to a hold after it's been scheduled for pick-up (i.e., associated with an appointment).
issue: https://github.com/rubyforgood/circulate/issues/359
* Added appointment relation in Hold model
* Created a helper method to cover the rule in card.
> 359-added rule to hide button

- app/helpers/holds_helper.rb
- app/models/hold.rb
- app/views/account/home/index.html.erb
_Describe the changes that you've made to the application in this PR._
Closes https://github.com/rubyforgood/circulate/issues/343
This should prevent a Member from scheduling a pickup for a hold if an item has not been returned. 
_Make a case for merging this work. This might include linking to a relevant issue._
This should provide a more consistent experience for the user. 
After spelunking, I needed a mechanism to test for pickup availability both in the holds helper and to control the schedule button in the account index view. So, I chose to update the `ready_for_pickup?` method on Hold versus pushing more …
> include loan ending in item availability

- app/views/admin/appointments/show.html.erb
Adds appointment start and end time in the following format: "1pm – 2pm" next to the date on the librarian appointment page.
Fixes #378.
**Before:**
**After:**
Since the `hour` time format uses `%l` which adds a blank space before the hour digit, I used spaces around the en dash, unlike the example in the issue which had no spaces.
> Display librarian appointment time next to date

- app/helpers/loans_helper.rb
- test/helpers/loans_helper_test.rb
Fixes the flaky test mentioned in #382 
Green tests at all times 😄 
- The test was failing due to timezone differences.
- When creating the due date in the test, the code is using `X.days.from_now` which is a rails method and uses the timezone specified in the app
- When humanizing the dates, the code is using `Date.today` which is a ruby method and uses the system time (UTC)
- Changed everything to use the rails date/time methods
Closes #382
> Fix flaky test

- app/controllers/account/appointments_controller.rb
- app/views/account/appointments/index.html.erb
- config/routes.rb
- test/controllers/account/appointments_controller_test.rb
Added cancelling of member's appointments by the member
Fixes Issue #354 
- Added the destroy method for appointments under the Account module
- Added test case for the same.
> Member can cancel appointment

- app/controllers/admin/borrow_policies_controller.rb
- app/models/loan.rb
- app/views/admin/borrow_policies/_form.html.erb
- db/seeds.rb
- test/controllers/admin/borrow_policies_controller_test.rb
- test/models/loan_test.rb
closes #344 
* Added `member_renewable` field to the admin borrow policy form
* Added an A tool to the seeds file
* Updated the `member_renewable?` method for loans to be false if the loan has an `ended_at` date
I suspect that this isn't working on staging because the `member_renewable` flag for the A policy is set to false.
**Admin form before**:
**Admin form after**:
**Member page with Renew button**
* Check that the `member_renewable` flag for the A policy is set to true
* I tried to add the `member_renewable` field to the table on the borrow policies index page, but the alignment ended up wonky, and I couldn't see immediately how to fix it.
> Fix renewal of A tools

- app/controllers/admin/members_controller.rb
- app/controllers/application_controller.rb
- app/controllers/users/sessions_controller.rb
- app/models/member.rb
- app/models/user.rb
- app/views/admin/members/_member.json.jbuilder
- app/views/admin/members/edit.html.erb
- app/views/admin/members/index.json.jbuilder
- app/views/admin/members/show.json.jbuilder
- config/routes.rb
- db/migrate/20201107024718_downcase_emails.rb
- db/schema.rb
- test/controllers/admin/members_controller_test.rb
- test/models/member_test.rb
This PR fixes some issues that arose from unintentionally creating extra User records when we were storing the user's location before login. This was made worse by a change that allowed for User records to have duplicate email addresses.
It also restores an admin's ability to destroy a member record to the UI to help with cases where someone signed up to be a member a long time ago and attempts to then signup another time, leading to confusion. Hopefully it'll be used sparingly, but we don't want to require someone with database access to help handle those situations.
> Member unique emails

- app/controllers/admin/appointments_controller.rb
- app/models/item.rb
- app/models/loan.rb
- app/models/loan_summary.rb
- app/nulls/null_attachment.rb
- app/nulls/null_borrow_policy.rb
- app/nulls/null_item.rb
- config/environments/development.rb
- test/models/item_test.rb
- test/models/loan_test.rb
Items that had been loaned couldn't be deleted because they were referenced from `Loan` objects. This change makes it so that even loaned items can be deleted by introducing the concept of a "deleted item".
Fixes #91 and a few other exceptions we've gotten that don't have GH issues.
* This PR introduces the [Null Object Pattern](https://thoughtbot.com/blog/rails-refactoring-example-introduce-null-object) into the codebase.
> Delete item fixes

- DOCKER.md
- Dockerfile
- docker-build.sh
- docker-compose.yml
Changed the way the docker image is built so that the current user owns all created files. 
- The call to `docker-compose build` is now done through a wrapper, to capture the uid of the current user. This is documented in DOCKER.md.
- The application no longer runs as root. This is more secure, but existing dev environments will need to delete root-owned files in tmp
Addresses issue #330
> Docker file owner

- .env.example
- app/lib/volunteer/google_calendar.rb
- app/views/volunteer/shifts/index.html.erb
We only want to allow up to three volunteers to staff any given shift as a part of our COVID precautions.
* This PR also renames the environment variable that holds the volunteer calendar ID to `VOLUNTEER_SLOT_CALENDAR_ID`, which is a much clearer name now that we also use a calendar for appointment scheduling.
> Limit volunteers to 3 per shift

- app/controllers/admin/members/memberships_controller.rb
- app/forms/membership_form.rb
- app/javascript/stylesheets/partials/_admin_memberships.scss
- app/javascript/stylesheets/partials/_index.scss
- app/lib/spectre_form_builder.rb
- app/models/loan.rb
- app/models/member.rb
- app/models/membership.rb
- app/views/admin/members/_member_details.html.erb
- app/views/admin/members/_profile.html.erb
- app/views/admin/members/memberships/index.html.erb
- app/views/admin/members/memberships/new.html.erb
- config/routes.rb
- db/migrate/20201129191804_make_memberships_pending.rb
- db/schema.rb
- test/controllers/admin/memberships_controller_test.rb
- test/factories/memberships.rb
- test/models/membership_test.rb
- test/system/admin/member_verification_test.rb
- test/system/admin/memberships_test.rb
- test/system/user_signup_test.rb
This changes memberships to have two states: active and pending. Pending memberships don't have a `started_on` or `ended_on` date and are mostly used when a new member first signs up. This allows the clock on their year-long membership to not start until they come in and verify their account, borrow a tool, etc.
We have a lot of folks who sign up online but don't make it in to see us for a while. This change avoids the situation where a lot of time passes and they get significantly less than a year before their membership needs to be renewed.
> Pending memberships

- app/controllers/admin/reports/memberships_controller.rb
- app/models/membership.rb
- app/views/account/members/show.html.erb
- app/views/admin/members/_member_details.html.erb
- app/views/admin/members/memberships/index.html.erb
- db/migrate/20201231181600_rename_membership_started_on_and_ended_on.rb
- db/schema.rb
- db/seeds.rb
- test/factories/memberships.rb
- test/models/membership_test.rb
- test/system/admin/memberships_test.rb
This PR contains the following changes:
1. A database migration to rename two columns on the `memberships` table.
2. Application and test level changes to reflect the renamed attributes on the `Member` model.
Relevant quote from https://github.com/rubyforgood/circulate/issues/263:
> memberships.started_on and memberships.ended_on store timestamps but are named using _on which indicates that they should be dates. Rename these columns to ended_at and started_at using a database migration to align their names with the values they store.
This PR closes https://github.com/rubyforgood/circulate/issues/263.
There are no UI changes on this PR. But I thought a before/after comparison of the Membership records would be helpful, so I'm including this screenshot:
* I didn't include previous database …
> [#263] Rename memberships started on and ended on columns

- app/views/admin/appointments/index.html.erb
Adds a tooltip to item names on appointment screen showing item number
Improves librarian experience, closes issue #423 
Tooltips show at a browser determined time, can be slow on certain browsers to appear.
> [Appointments] Hovering item link shows item number

- app/views/admin/appointments/_checkouts.html.erb
- app/views/admin/appointments/show.html.erb
Disable the check-out all and check-out button on the appointments page if a user is unverified or inactive
Closes issue #427. 
Reused alert banners from member's page
Covered both cases of Unverified and Inactive individually, and links to verify and active work as expected
> Disable check out buttons for unverified users on Appointments

- .env.example
This PR has goal to add Database credentials to .env exemple
> add database credentials to dotenv example

- app/views/account/members/show.html.erb
Displays additional member fields to the Member Account Settings show page.
Resolves this issue https://github.com/rubyforgood/circulate/issues/296!
Before:
After:
I pulled the some code from existing checkbox tag implementation elsewhere in the repo, and decided to keep the label text unbolded. Open to suggestions. 🙂
> Member Account Settings: Display all editable fields

- README.md
I went through the setup instructions and it looks like the default admin email has changed in `seeds.rb`, but not in the README. The example.com version works, so I updated the docs here.
Without it I wasn't able to log in after running the setup commands
> Fix default admin email in README

- app/controllers/renewal/payments_controller.rb
- app/controllers/signup/payments_controller.rb
- app/lib/square_checkout.rb
- test/controllers/signup/payments_controller_test.rb
- test/lib/square_checkout_test.rb
Updates the Square reference ID for membership orders to include the membership creation date before the member ID.
Closes #441
* I made `date` a parameter of `checkout_url` and passed `Date.today` from the controller because I'm assuming that will always correspond to the membership creation date. Let me know if any of that isn't what you're expecting!
> Update membership Square order number

- test/controllers/signup/payments_controller_test.rb
Cleans up the flaky test from #449 with the `freeze_time` helper
It looks like the controller test fixed here has been failing on some PRs, so this should clean that up
> Fix flaky test with freeze_time

- README.md
added the usernames from seeds.db to ReadMe
Allows folks not to have to comb through seeds.db to get user accounts.
Unfortunately, risks getting out of date as we update the user list, but it's most likely we'll just add accounts, rather than this list becoming inaccurate. Also explicitly says that it's in seeds.db in case folks need to look it up.
> added explicit usernames to ReadMe

- lib/tasks/devdata.rake
This fixes an issue where audits were being created for dev data without a `current_user` set. This was causing the item edit history page to throw an error when it attempted to call methods on an audit's user (which was `nil`).
Developers should be able to view any of the pages in the app using the dev data.
> Set current_user when loading dev data.

- app/controllers/admin/renewal_requests_controller.rb
- app/views/account/home/index.html.erb
- app/views/admin/renewal_requests/index.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- db/schema.rb
- test/controllers/admin/renewal_requests_controller_test.rb
Adds a page for admins to view renewal requests and apply filters based on status. Also fixes an env var typo in the user loans template and re-runs `standardrb` since it looks like my lefthook config wasn't working earlier.
Implements the changes from the designs in #307
Everything was based on some existing admin views, so it shouldn't be too different, but let me know if my call to `includes` isn't loading all the models we need. I didn't see any duplicate queries locally, but want to be sure since I'm still getting a hold of the schema
> Allow admins to view renewal requests

- DOCKER.md
Updates the docker docs to mention the `docker-build.sh` script. It's important to use this script so that files created inside containers are owned by the current user outside docker.
> Update docs to reference the docker-build.sh script.

- app/controllers/account/home_controller.rb
- app/controllers/admin/renewal_requests_controller.rb
- app/lib/activity_notifier.rb
- app/models/loan_summary.rb
- app/models/renewal_request.rb
- app/views/account/home/index.html.erb
- app/views/admin/renewal_requests/index.html.erb
- app/views/member_mailer/_summaries.erb
- app/views/member_mailer/summary.mjml
- test/controllers/admin/renewal_requests_controller_test.rb
- test/lib/activity_notifier_test.rb
- test/system/admin/renewal_requests_test.rb
Adds support for admins approving and rejecting renewal requests based on the descriptions in the issues with some caveats listed in the notes here. Also updates the member loan update email to mention rejections, since renewals are already covered
Closes #305 and #306.
* I updated the `active_on` scope for loan summaries to check renewal request updates, and moved it to keyword interpolation to be a little more clear since the query is pretty long
* The issue about rejecting renewals says the status column for members should include a longer message telling people to schedule a time to return items, but that didn't fit in the table so I used the shorter version in the screenshot
> Allow admins to approve, reject renewals

- app/helpers/items_helper.rb
- test/helpers/items_helper_test.rb
* Fixes #469 by specifying that thumbnails should not perform cropping.
* Adds test coverage of `item_image_url` helper.
> Avoid cropping when using ImageKit.

- app/controllers/account/appointments_controller.rb
- app/helpers/appointments_helper.rb
- app/helpers/holds_helper.rb
- app/helpers/loans_helper.rb
- app/models/hold.rb
- app/views/account/appointments/index.html.erb
- test/models/hold_test.rb
- test/system/appointments_test.rb
- test/system/member_holds_test.rb
* This corrects a few bits of logic around appointments and holds for uncounted items.
* The way that appointment times were displayed was unified to improve consistency.
> 477 - Allow multiple members to create an appointment for the same item

- app/views/account/appointments/_form.html.erb
- app/views/account/appointments/new.html.erb
If the member doesn't have any items on hold or to return, show a message and disable the form fields on the create appointment page.
Resolves this issue: https://github.com/rubyforgood/circulate/issues/466
When you can't make an appointment...
When you can make an appointment! 🎉 
I suppose I could also hide the form fields instead of disabling, whatever feels best
> Show message if member can't make an appointment

- app/controllers/items_controller.rb
- test/controllers/items_controller_test.rb
* Fixes #474.
* There was a bug where items that were retired or pending would appear on the category listing pages.
> 474 - Hide retired and pending items from inventory page.

- app/controllers/searches_controller.rb
- test/controllers/searches_controller_test.rb
Right now, an empty search query loads a page that lists every item. This, as you can imagine, is bad for the health of the server and the patience of the user.
This PR checks for a sufficiently lengthy query and shows an error if there isn't one.
> Avoid loading every item for a blank search query

- app/controllers/admin/appointments_controller.rb
- app/javascript/stylesheets/partials/_appointment_form.scss
- app/javascript/stylesheets/partials/_index.scss
- app/views/account/appointments/new.html.erb
- app/views/admin/appointments/_form.html.erb
- app/views/admin/appointments/edit.html.erb
- app/views/admin/appointments/show.html.erb
- config/routes.rb
- test/controllers/admin/appointments_test.rb
Adds a form for staff and admins to modify appointment times and a link from the appointment detail page to get to the form. Also adds a helper method for converting an appointment's start and end into a `time_range_string` for the select input.
Closes #237
* Is there a reason for including `current_appointment` as a helper here instead of something like `before_action :set_appointment`?
* I copied `load_appointment_slots` from the other appointments controller, but that could probably be abstracted somewhere. That also might be better as a `before_action`
> Allow staff to modify appointment times

- app/controllers/items_controller.rb
- app/helpers/items_helper.rb
There was an N+q query on the items index. We were making a query to the database for every item to determine what status label to display (if there are active holds, it will show that the item is on hold). This PR eager loads the active holds so to avoid those additional queries
> Eager load active holds to avoid a query per item on the item index

- app/lib/activity_notifier.rb
- app/mailers/member_mailer.rb
- app/views/member_mailer/_staff_daily_renewal_requests.erb
- app/views/member_mailer/staff_daily_renewal_requests.mjml
- lib/tasks/email.rake
- test/mailers/previews/member_mailer_preview.rb
Adds a task for sending a daily summary of renewal requests to library staff
Closes #346
* The email goes to both staff and admins, but should this just go to staff?
* I reused `MemberMailer` instead of adding a separate mailer because all of the boilerplate seemed the same and it didn't seem worth splitting out for now
* I based the query for determining whether a request was made on the current day on the `LoanSummary` `active_on` scope, but it's not clear to me why that works with UTC instead of the local time
* I'm filtering on the user role database enum directly because I didn't see any case where we filter for multiple roles, not sure if a scope would make more sense
> Send staff daily email of renewal requests

- app/helpers/holds_helper.rb
This PR addresses an issue where the hold position shown on a member's page was incorrect.
> Use method on hold to determine place in line.

- app/models/item.rb
- test/models/item_test.rb
Adds an `after_update` callback to items so that whenever an item is changed to an inactive status all of its active holds are made inactive.
Closes #475 
* The check for whether the status is changed to `maintenance` or `expired` is more verbose than I expected because `saved_change_to_attribute?` doesn't seem to support multiple values in the `to:` argument. And not sure if this is the expected behavior, but `status` in the callback is a string instead of an int so I'm converting it back in `Item.statuses[status]`
> Clear holds when an item is made inactive

- app/controllers/account/appointments_controller.rb
- app/models/appointment.rb
- test/controllers/account/appointments_controller_test.rb
Adds a conditional validation to `Appointment` making sure that the appointment starts before the earliest hold expiration. 
Closes #375
* I was initially looking at using a validation context, but it looks like those require calling `save` or `valid?` after using `assign_attributes` which forces related models to update before validation. Using an `attr_accessor` to determine whether or not a member is updating the record seemed to be the simplest way to only apply the validation to members and not admins
> Require member appointments be before holds expire

- app/views/admin/borrow_policies/index.html.erb
- test/controllers/admin/borrow_policies_controller_test.rb
This fixes an exception that was raised when operating the software with an empty database. This could cause confusion for new users or developers as it obscured the cause of the issue.
> Remove reference to nonexistant route. Closes #528.

- app/helpers/admin_helper.rb
- app/views/admin/appointments/index.html.erb
Occasionally a member will schedule multiple appointments. This PR groups them together in the appointment list while we improve the system to help members edit existing appointments instead of creating new ones.
> Show all of a member's appointments together regardless of their time

- app/controllers/admin/appointments_controller.rb
- app/helpers/admin_helper.rb
- app/helpers/application_helper.rb
- app/javascript/controllers/appointments_index_controller.js
- app/javascript/stylesheets/partials/_admin_appointments.scss
- app/views/admin/appointments/_appointment.html.erb
- app/views/admin/appointments/index.html.erb
This change moves completed holds to the bottom of the appointment page so they are out of the way but reviewable.
It also collapses really long lists of items to pick up so that the appointments are easier to browse.
> Move completed holds to the bottom of the page.

- app/controllers/account/appointments_controller.rb
- app/controllers/admin/members/appointments_controller.rb
- app/controllers/concerns/appointment_slots.rb
- app/helpers/date_helper.rb
- app/javascript/stylesheets/application.scss
- app/models/appointment.rb
- app/views/admin/members/_member_details.html.erb
- app/views/admin/members/_profile.html.erb
- app/views/admin/members/appointments/_form.html.erb
- app/views/admin/members/appointments/index.html.erb
- config/routes.rb
- test/controllers/admin/members/appointments_controller_test.rb
- test/models/appointment_test.rb
Allows librarians to create appointments in the member section of the admin page. I tried to base this on existing functionality so let me know if there's anything that should change!
Closes #358 
* I based the conditional validation on #519
* I moved the `load_appointment_slots` into a concern now that we're using it in more than one place, but let me know if there's a better spot
* Adding the new "Appointments" tab causes the line to wrap, so not sure if we want to address that
> Allow librarians to create appointments

- package.json
- yarn.lock
In versions of webpacker prior to 5.4.0, webpacker has a dependency on
`node-sass`, which has a dependency on `node-gyp`. This dependency seems
to be causing problems with Apple's slicon chip. In 5.4.0, this
dependency is removed in favor of `sass`, which is the default
implemenation written in dart. `sass` does not depend on `node-gyp`.
Running `yarn` with version lower that 5.4.0 always fails on install `node-sass` even when updating python to python3. After upgrading I am able to run `yarn` and the app successfully runs. However, running the test suite results in multiple failures. These failures do not seem to be caused by `webpacker` but I am not 100% sure. Are there failing tests when using version 4?
> Bump webpacker from 4.0.2 to 5.4.0

- app/javascript/stylesheets/partials/_admin_appointments.scss
- app/views/admin/appointments/_appointment.html.erb
closes #468 
Add colored labels to distinguish between pick-ups and drop-offs on admin appointment index.
Admins/librarians need to be able to easily distinguish between the two types of appointments.
> Add label to distinguish between pick-ups and drop-offs

- app/models/hold.rb
- test/models/hold_test.rb
Holds will now wait for 7 days before the item is offered to the next person in line.
We have a decent number of items that sit for 14 days when someone no longer wants them. This will shorten that cycle and help more members access the items they are waiting for.
> Make holds 7 days instead of 14.

- app/models/member.rb
This PR fixes a bug where members who have a deactivated account (which is usually the result of duplicate signups) are unable to renew their memberships.
> Scope uniqueness validation to ignore deactivated accounts.

- app/models/event.rb
- test/models/event_test.rb
Show the full event times on the shifts admin page.
> Include minutes in event times

- app/controllers/admin/items_controller.rb
- app/helpers/items_helper.rb
- app/views/admin/items/_form.html.erb
- app/views/admin/items/_profile.html.erb
- db/migrate/20210722214912_add_item_location_fields.rb
- db/schema.rb
* Adds two fields where we can experiment with storing location info for tools.
* Also rearranges the item form to reduce scrolling by putting multiple fields on one line for desktop users.
> Add area and shelf fields to item

- app/controllers/items_controller.rb
- app/helpers/items_helper.rb
- app/javascript/controllers/collapse_controller.js
- app/javascript/controllers/tree_nav_controller.js
- app/javascript/stylesheets/application.scss
- app/javascript/stylesheets/partials/_index.scss
- app/javascript/stylesheets/partials/_items_index.scss
- app/javascript/stylesheets/public.scss
- app/javascript/stylesheets/tree_nav.scss
- app/models/category_node.rb
- app/views/items/index.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_time_override.html.erb
This change replaces the existing category list (which had some semantic, accessibility, and usability issues) with a collapsible tree.
* In addition to addressing the issues mentioned above, this will allow us to have more granular (and hopefully more useful) categories as they won't all display on the page by default.
* There are some other accessibility improvements including a skip link that were added while developing this feature.
* The categories now appear on the left of the page to better reflect the information hierarchy.
* Categories are hidden on mobile, and a button is provided to toggle their display.
> Category tree nav for inventory

- app/mailers/user_mailer.rb
- config/initializers/devise.rb
Overrides the Devise default mailer to add an `after_action` creating a notification whenever a user requests a password reset.
#632
Overriding the Devise mailer seemed like the most straightforward way and shouldn't have any other side effects
> feat: create notification on password reset

- app/views/account/appointments/_form.html.erb
- app/views/admin/items/_form.html.erb
Just tackling some small tickets from the board.
- Add reminder text when scheduling an appointment
- Update admin new item form field "Other names" -> "Other names and keywords"
Resolves issues https://github.com/rubyforgood/circulate/issues/605, https://github.com/rubyforgood/circulate/issues/606
> Add scheduling appointment reminder text and update admin new item form text

- test/application_system_test_case.rb
Fix issue https://github.com/rubyforgood/circulate/issues/644
When using docker environment, the driver (`headless_chrome_in_container` or `chrome_in_contaier`) is set, but the driver being used is the one passed to `driven_by` method, which is `headless_chrome` or `chrome`. Because the driver in use does not use Chrome in the `selenium_chrome` container, and there is no Chrome installed in `web` container, Rails cannot find Chrome browser to run test.
I changed the code so that the correct driver is passed into `driven_by` method.
To let developers with Docker environment run `docker-compose exec web rails test`.
Because we've already used `driven_by` method, I think we don't need to setup `Capybara.javascript_driver` and `Capybara.current_driver` so I removed those lines.
I have tested …
> Use "in_container" driver when in docker setup

- config/application.rb
Updates the configuration to start from the 6.1 defaults, but stays pretty conservative about going against defaults if they seem to change behavior.
#631
* `legacy_connection_handling` is required to be true or the tests will fail. This could be possible for production, but to be cautious I'm applying it for all objects for now
* `form_with_generates_remote_forms` is required to be true otherwise multiple tests fail
* The rest are mostly assumptions about what could cause changes, in particular on ActiveStorage and not wanting to change anything with timezones
> refactor: update to 6.1 defaults

- test/application_system_test_case.rb
This fixes the way we use registered drivers with `driven_by`, so that system test can run with those custom defined drivers.
Solve https://github.com/rubyforgood/circulate/issues/660
About my approach here:
I checked the signature of `driven_by` and found that we need to pass the driver to the first argument, and the browser to `using:`. In our case here, when we call `Capybara.register_driver`, we define a driver, not a browser, so that `driver` should be passed as the first argument.
https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/system_test_case.rb#L154-L158
The default value for `using:` is `:chrome`, so I also checked if there is any problem when we don't pass `using:` into `driven_by`. It seems like when we pass a custom driver, value of `using:` is …
> Fix system test for custom drivers

- app/models/categorization.rb
- app/models/item.rb
- lib/tasks/export.rake
CTL wants to edit item categories in a bulk fashion, so we're exporting the categories and items to spreadsheets and will reimport the changes when that process is complete.
> New export function for categories

- .env
- README.md
This removes the assumption that folks will be connecting with a certain database username and password. It also adds a mention to the README to show developers how to customize these settings on their machines.
Most users aren't going to connect with the user `postgres`. It's better to default to empty values and have folks fill these in as needed than have a default that isn't useful for most people.
> Remove credentials for database

- app/lib/google/calendar.rb
- app/lib/volunteer/month_calendar.rb
This fixes a bug where volunteer shifts were appearing on the wrong day of the week. I also tweaked the date parsing to consider a timezone in the event JSON, although in testing this didn't seem to matter since the values are all in UTC anyway.
> Calendar bugs

- app/javascript/stylesheets/partials/_admin_appointments.scss
- app/views/admin/appointments/_checkouts.html.erb
Adds some spacing to the admin checkout buttons. To make resizing and spacing easier I've got the flex direction set to column consistently
#670
> increase spacing on admin checkout buttons

- lib/tasks/email.rake
Updates the rake task for membership renewal emails to pull users 30 whose memberships expire 30 days from the current date
Closes #442
* I'm using the [`Date#all_day`](https://apidock.com/rails/DateAndTime/Calculations/all_day) helper to return a range in UTC of the full datetime for a given day. This should handle any timezone issues
> Send membership renewal email 30 days before expiration

- app/controllers/admin/members_controller.rb
- app/views/admin/members/_fields.html.erb
- app/views/admin/members/_form.html.erb
- app/views/admin/members/_member_details.html.erb
- db/migrate/20210911202001_add_pronunciation_to_members.rb
- db/schema.rb
- test/factories/members.rb
- test/models/member_test.rb
* Add pronunciation column of string type to members table
* Show pronunciation only in librarian view's show and edit pages
Resolve https://github.com/rubyforgood/circulate/issues/630
* Librarian view
* Show with pronunciation
* Show without pronunciation    
* Edit
* Member view (no change)
* Show
* Edit
* Sign up form
* I don't see any existed integration test for show and edit member page of librarian view, so I only add a model test. Is that OK? 
> Add member pronunciation to librarian view

- app/views/layouts/application.html.erb
Based on the conversation I'm re-initializing WeGlot on every page load. I haven't dug too deeply into the WeGlot docs, so I'm not sure if there's another function I should be calling here. From some local testing it looks like `turbolinks:load` is fired on initial page load as well so I'm always calling it as an event handler
#627
> re-initialize weglot on turbolinks load

- CONTRIBUTING.md
- README.md
Updating the install instructions in the README to include installing circleci. Corrected a typo (tails instead of rails) in the CONTRIBUTING guide.
Make contributing setup easier for new contributors
> Add circleci cli install to README, fix typo in CONTRIBUTING

- app/views/admin/appointments/_checkins.html.erb
- app/views/admin/appointments/_checkouts.html.erb
- Commented out since we may want these back later
Remove buttons to "Check out all" and "Check in all"
See #669 -- buttons are currently causing errors in workflow. May want to reimplement later.
Before:
After:
N/A
> Comment out check out and check in all buttons

- app/views/layouts/steps.html.erb
Adds an event listener to weglot implementation in ```steps.html.erb```
See Issue #627
N/A
I *think* this will fix the issue with translator not showing up on stage pages, but I haven't been able to test since this is only implemented in prod. I'm open to ideas on how to test this.
- [ X ] I am interested in feedback but don't need to make the changes myself.
> add event listener to weglot in steps.html.erb

- test/system/user_signup_test.rb
There were two tests that would fail occasionally. This PR extends the timeout on the assert-selector in those two tests to allow more time for the background job to complete.
> extend wait on two flaky tests Fixes #729

- app/models/item.rb
- test/factories/item_attachments.rb
- test/models/item_test.rb
- Delete all attachments along with an item
- Update FactoryBot for Item Attachment
- Add test for deleting item with attachments
See #473
N/A
N/A
> Fix bug in item deletion

- test/application_system_test_case.rb
- test/system/admin/notes_test.rb
This adds a method that clears the js console errors and prevents them from littering the test output when they are caused intentionally.
Any noise in the test output has the potential to distract a developer from seeing actual errors versus the extraneous output. In cases where you will cause a console error intentionally, you should be able to prevent that from showing in the test output.
There are two ways you can use the `ignore_js_errors` method in your tests: inline and block form.
In the block form, surround the code you know will cause the errors.
```ruby
test "it gives an error when you submit without filling in the form" do
ignore_js_errors(reason: "Creating without filling in the fields gives a 422") do
visit edit_item_url(@item)
click_on "Submit"
expect(page).to …
```
> Add method to swallow js errors when they are intentional

- app/views/admin/appointments/_checkins.html.erb
- app/views/admin/appointments/_checkouts.html.erb
When a librarian views an appointment, the item number is now a hyperlink to the item page.
See issue #677
Before:
After:
Hyperlink leads to this page:
One note -- do we want to link to the member view or the librarian view? Right now, the link goes to the member view.
> 677 make item numbers into hyperlinks

- app/controllers/items_controller.rb
- app/views/items/index.html.erb
- Updates view inventory page to automatically sort by date added instead of name
- Changes "added" tab to "date added"
See Issue #671
Original View Inventory Page:
Updated View Inventory
N/A
> update item index to automatically sort by date added

- app/lib/volunteer/day.rb
- app/views/volunteer/shifts/_month_calendar.html.erb
- test/system/volunteer/shifts_test.rb
This fixes a system test that was very sensitive to the current day. It replaces naive text matching with a `data-test-date` attribute, which should insulate this test from timezone and other temporal shenanigans in the future.
We have a broken test on the main branch.
> fix: use attribute to find day in shift system test

- app/models/loan.rb
- app/views/account/home/index.html.erb
- test/models/loan_test.rb
This method had a reference to `Time.current` that was causing tests to break when loans straddled a daylight savings time change and was additionally really difficult to reason about. There was a comment mentioning that it could be removed, so I went ahead and did that.
It's possible that this will make renewals more open than we wish, but we can lock things back down when we identify the situation where that is relevant.
> Remove Loan#within_borrow_policy_duration method

- config/initializers/pagy.rb
By default, Pagy throws an exception when given a page parameter greater than the number of pages available in a result. This change adds in [Pagy's Overflow extra](https://ddnexus.github.io/pagy/extras/overflow) (included in the gem already) and configures overflow to return the last page of results when page param is too large (in other words, when page overflows).
Closes #850, addressing an unhandled exception when a request is received with a page parameter that's too high.
This is probably the simplest fix for quieting the unhandled exception.
While the only "user" experiencing this error is a web crawler, returning the last page of results (say, page 10) when ever a page param is given that overflows (say, page 11 or 100, or 1,000,000) implies at the protocol level of HTTP that the …
> configure Pagy to return last page on overflow

- app/lib/activity_notifier.rb
- app/mailers/member_mailer.rb
- app/views/member_mailer/_overdue.erb
- app/views/member_mailer/_summaries.erb
- app/views/member_mailer/overdue_notice.mjml
- app/views/member_mailer/overdue_notice.text.erb
- app/views/member_mailer/summary.mjml
- app/views/member_mailer/summary.text.erb
- test/lib/activity_notifier_test.rb
It changes overdue notice emails to only list overdue items, instead of all items that a member has recently interacted with.
See individual commit messages for more detail.
Fixes #814
Decluttering overdue notice emails, it makes it clearer for members what items are overdue and need to be returned or renewed.
https://user-images.githubusercontent.com/14851208/141201125-66be895f-db30-441d-8c6c-9edbd2d89f64.mov
I decided to create new templates specific for the overdue notice emails. Instead of adding logic to the summary email templates, this approach allowed me to remove some conditional logic from there.
This is best reviewed commit by commit as they are self-contained and with explicit commit messages.
_Please choose one of the following to help the project maintainers provide the …
> Only list overdue items in the overdue notice emails

- app/controllers/application_controller.rb
- app/controllers/concerns/page_attributes.rb
- app/controllers/items_controller.rb
- app/controllers/searches_controller.rb
- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- test/controllers/concerns/page_attributes_test.rb
This PR adds page titles to some of the public inventory pages.
Titles are crucial for usability and accessibility- otherwise the entries in the browser history are indistinguishable.
* I pulled some of the code from an older app I have. It's not open source, but this pattern worked fairly well for that one.
> feat: Add inventory page titles

- app/controllers/admin/reports/memberships_controller.rb
- test/controllers/admin/reports/memberships_controller_test.rb
The tenant-scoping code adds some additional where clauses to queries throughout the system. This report needed to be tweaked so that this auto-scoping worked properly.
> fix: Select library_id column to prevent tenant scoping from breaking memberships report

- app/views/admin/appointments/_checkins.html.erb
- test/controllers/admin/appointments_controller_test.rb
There was a local variable that was misnamed and causing the appointment page to break when a member was returning an item.
> fix: Correct local variable name to prevent undefined variable error

- app/views/account/home/index.html.erb
There is an issue where we aren't showing the renewal request buttons for loans that are renewals.
> fix: show renewal buttons for renewals on account home

- app/jobs/neon_member_job.rb
- app/models/member.rb
- test/models/member_test.rb
Creates a new job for running the Neon CRM sync in the background
https://github.com/rubyforgood/circulate/pull/789/files#r735003294
* It looks like `sucker_punch` is a pretty standard implementation of ActiveJob, but I might have missed something
> feat: create job for async neon crm updates

- app/controllers/admin/holds_controller.rb
- app/controllers/admin/settings/closing_controller.rb
- app/forms/extend_holds_form.rb
- app/lib/spectre_form_builder.rb
- app/models/hold.rb
- app/views/admin/settings/closing/index.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- db/migrate/20211120222110_add_expires_at_to_holds.rb
- db/migrate/20211120222255_set_expires_at_on_existing_holds.rb
- db/schema.rb
- lib/tasks/holds.rake
- test/controllers/account/appointments_controller_test.rb
- test/factories/holds.rb
- test/forms/extend_holds_form_test.rb
- test/models/hold_test.rb
This PR changes how hold expiration works. The date that holds expire is now recorded when the hold is "started" instead of being determined dynamically within queries. This allows us to adjust the hold expiry date in situations such as temporary closures.
A new admin page has also been added with just such a form.
CTL is going to be closed this week, and we don't want folks to lose their place in line because their holds expire when we're not open.
> Holds record and can extend expiration date

- Dockerfile
This may be a known issue or have an undocumented workaround but in following along with `DOCKER.md` and running `docker_build.sh`, I was seeing a non-zero exit status with the following output:
```
Step 17/25 : RUN yarn global add heroku
---> Running in ae2440267056                                                                     
yarn global v1.22.10                                
[1/4] Resolving packages...                                                                                          
warning heroku > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning heroku > @heroku-cli/plugin-git > …
```
> Update dockerfile to explictly add node-gyp

- app/views/gift_purchaser_mailer/confirmation.mjml
- app/views/gift_purchaser_mailer/confirmation.text.erb
- app/views/layouts/mailer.html.mjml
- app/views/layouts/mailer.text.erb
- app/views/signup/confirmations/_hours.html.erb
This PR:
- removes duplicate information in gift membership email
- brings plain text confirmation email on par with the html confirmation email (content parity)
- introduces some minor improvements (see commit messages for detail)
_**This is best reviewed commit by commit.**_
Fixes https://github.com/rubyforgood/circulate/issues/860
https://user-images.githubusercontent.com/14851208/143787665-2fada2a9-e87e-4ac7-94b3-f691bed83b9c.mov
I have the time and interest to make additional changes to this PR based on feedback.
> Remove duplicate information in gift membership email

- app/models/event.rb
- lib/tasks/sync.rake
Calendar syncing has been broken for a while since we deployed some of the multitenant code. Events were failing to save to the database, but we didn't notice because no exceptions were being raised.
This PR:
* Raises exceptions when Events don't save. These will appear in our usual tools and we'll be notified
* Sets the current tenant around the calendar syncing to that events will save without error.
> Set tenant when syncing calendars.

- app/views/member_mailer/renewal_request_updated.mjml
- test/mailers/member_mailer_test.rb
- test/mailers/previews/member_mailer_preview.rb
A bug in one of the email templates is breaking the messages we send to members when their renewal requests are responded to by staff.
We'd like our emails to reach our members 😄 
* The issue only came up when an item had an attached image, and our tests didn't create items with images. This has been addressed.
> fix: reference to wrong instance variable was breaking renewal emails

- app/controllers/admin/dashboard_controller.rb
- app/javascript/stylesheets/admin.scss
- app/views/admin/dashboard/index.html.erb
This PR adds some very basic stats to the Circulate Dashboard. We'll iterate on what is important enough to include here.
Folks working at the library need a high level understanding of what is going on, and adding some statistics can help with that.
> Start putting something on the dashboard.

- app/helpers/items_helper.rb
- app/models/item.rb
- test/factories/loans.rb
- test/helpers/items_helper_test.rb
Resolves #888 
Overdue items now appear with an "Overdue" status label, instead of "Checked Out".
Also, the method `ItemsHelper#item_status_class` is deleted since it is not used anywhere.
This will help members avoid putting items on hold that are overdue (and unlikely to return soon or possibly at all).
The same change appears at the item page's "Status" label.
> add 'Overdue' item status label

- app/controllers/concerns/lending.rb
- test/controllers/concerns/lending_test.rb
This fixes a bug where a loan that was renewed after being added to an appointment would be shown as being checked in.
This bug could create confusion and cause staff to not check in items that should be checked in.
* I did this by updating the `loan_id` association on `AppointmentLoan`. The other option was to change `AppointmentLoan` to be associated with `LoanSummary` instead of `Loan`, but since that is a more intrusive change I went with this option.
> Move appointment loans to the renewal when a loan is renewed.

- app/controllers/admin/members/memberships_controller.rb
- app/forms/member_signup_form.rb
- app/forms/membership_form.rb
- app/javascript/stylesheets/admin.scss
- app/javascript/stylesheets/overrides.scss
- app/models/membership.rb
- app/views/admin/members/_profile.html.erb
- app/views/admin/members/memberships/index.html.erb
- app/views/admin/members/memberships/new.html.erb
- test/system/admin/memberships_test.rb
This PR allows admins to renew memberships for members before their current membership expires. This has started coming up from time to time.
It's better to be able to do this when members ask than remember to do it when the time comes. 
* The system already mostly handled this, so this change is mostly adding a link to the existing form and a few UI tweaks to accommodate having multiple "started" memberships.
> Admins can renew memberships early unless there is a pending membership.

- app/models/hold.rb
- test/models/hold_test.rb
This change fixes an issue where the holds system that starts holds stopped working because an item's status was set to "retired" after it was placed on hold.
We need the holds system to be resilient and always running.
* This fixes the symptom, but not the underlying cause.
> Gracefully handle retired items being on hold. Fixes #946

- app/views/items/place_hold_on/_item_already_with_a_hold.html.erb
Hides the schedule appointment link for an item if the hold is not ready for pickup
#950 
Before:
After:
> Hide schedule appointment link if hold is not ready

- app/views/account/appointments/_form.html.erb
- test/system/appointments_test.rb
closes #940 
Instead of showing the appointment form, we show a blurb explaining they cannot make an appointment with no holds nor returns.
This makes the appointment page less cluttered for folks who can't make an appointment because they don't have a hold nor an item to return.
Before | After
--- | ---
* I moved the form into an if/else instead of it living outside the if. I handled it inside _form, so if this form is used anywhere else, the change will also apply.
_My weekday schedule is a little full, but every weekend, I have time to contribute._
> Hide Appointment Form if there's no hold nor return.

- DOCKER.md
Added additional info to DOCKER guide on some things that tripped me up during setup:
1. could only access the local site through localhost:3000
1. reduce confusion around system specs in rails
Putting these suggestions in the DOCKER guide can prevent developers googling how to run a single system spec, and getting very confused when all their system specs run, even though they passed a file. It could also help first-time rails devs know to check localhost:3000, if the http://chicago.circulate.local:3000 doesn't work for them.
Before | After
--- | ---
_I have limited availability during the week, but normally set aside time on the weekends to contribute to open-source._
> Readme updates

- app/models/hold.rb
- app/models/item.rb
- test/models/hold_test.rb
- test/models/item_test.rb
Pauses holds instead of deleting them when an item is put into maintenance mode. I generally followed the steps mentioned in the issue but added an additional callback for updating the `next_hold`
#629
* I'm calling `update_columns` instead of `update!` for clearing the `next_hold` to avoid validations. This was because once the item is updated to `maintenance` all hold validations fail because the item is no longer holdable. Initially I tried to fix this by moving the callback into `before_save`, but I still ran into the same issue
> Don't delete holds when item goes maintenance

- docker-compose.yml
- test/application_system_test_case.rb
This PR resolves a few issues (including #978) involving deprecation warnings or errors from the selenium driver configuration getting out of date with the latest updates to the library.
System tests should work for everyone, and ideally there should be no deprecation warnings to add noise to the test output.
* There is some duplication in the configuration that we can look into addressing in the future, but in the past we needed to control each combination of headless/dockerness individually. So I'm inclined to leave the duplication there for now should we need to do that again.
* It's possible that we don't need all of the options (in particular `disable-dev-shm-usage`) but I didn't fully test this in all situations.
_Please choose one of the following to help the project maintainers …
> Selenuim config update

- app/controllers/admin/item_holds_controller.rb
- app/views/admin/item_holds/index.html.erb
- test/system/admin/items_test.rb
Thanks to @jutonz for pairing with me on this 🙂 
Admins can toggle to see an item's active or inactive holds.
Resolves issue https://github.com/rubyforgood/circulate/issues/980
A few open questions:
1. We assumed "previous/historic" holds (as written in the [issue](https://github.com/rubyforgood/circulate/issues/980)) meant inactive, but it looks like there are more granular states. Was this the correct assumption or should the list filter on something else?
2. Related, we labeled the buttons "Active" and "Inactive" based on what I saw in the code. Will that work or there more user-friendly terms to use here? 
3. Inactive holds shows the same data in the table as active holds, but it looks like some of the columns might not be relevant, or that some additional information for inactive …
> Allow admins to view previous holds

- app/controllers/admin/appointment_completions_controller.rb
- test/controllers/admin/appointment_completions_controller_test.rb
This fixes a bug where appointment without items couldn't be marked as complete.
> Set staff_updating to avoid empty appointment validation issue

- app/controllers/admin/items_controller.rb
- app/javascript/stylesheets/application.scss
- app/views/admin/items/_item_panel.html.erb
- app/views/admin/items/_items.html.erb
- app/views/admin/items/_profile.html.erb
- app/views/items/_item_panel.html.erb
- app/views/items/index.html.erb
- app/views/items/show.html.erb
Displays the number of active holds in a few places:
* The items lists in both public inventory and admin side
* The inventory item page
* The admin item page
See #984
> Item hold counts

- app/controllers/admin/categories_controller.rb
- app/helpers/items_helper.rb
- app/models/categorization.rb
- app/models/category.rb
- app/models/category_node.rb
- app/models/item.rb
- app/views/admin/categories/index.html.erb
- db/migrate/20220330165641_add_item_counts_to_category.rb
- db/migrate/20220330175925_update_category_nodes_to_version_3.rb
- db/migrate/20220403224122_add_unique_index_to_category_nodes.rb
- db/schema.rb
- db/views/category_nodes_v03.sql
- lib/tasks/categories.rake
- test/models/categorization_test.rb
- test/models/category_node_test.rb
- test/models/category_test.rb
- test/system/admin/items_test.rb
This PR updates the category counts to consider item statuses. The category cound only include items that have an `active` or `maintenance` status.
This fixes the issue where CTL have 500 seeds shown in the category listing but only about half that number when browsing since so many are actually retired.
It's also an issue for smaller categories, where the numbers are confusing and make it look like the site is broken or there are items just missing.
We now store item counts as a Hash that's stored in a JSONB column in the database. This persists the number of items with each status in the category, and we can use that information to then calculate how many items are in categories themselves or in their children.
We'll need to run `rails categories:update_category_counts` in production …
> Item status category counts

- app/helpers/items_helper.rb
- app/models/categorization.rb
- app/models/category.rb
- db/migrate/20220421204258_update_category_nodes_to_version_4.rb
- db/migrate/20220422172531_remove_item_counts_from_categories.rb
- db/schema.rb
- db/views/category_nodes_v04.sql
- lib/tasks/categories.rake
- test/models/category_node_test.rb
- test/models/category_test.rb
- test/system/item_filtering_test.rb
Changes the implementation of the category counts to handle items being counted more than once due to belonging to more than one category with a shared parent category.
The item counts within categories were appearing to be wrong, which was confusing to users.
* The previous implementation counted items assigned to each category, grouped by the item status. These counts were then rolled up by the `category_nodes` view. This was faster but made it impossible to prevent items from being counted more than once.
* This implementation does away with the category-level counts and does all the counting in the `category_nodes` view. This is slower (the view is take about 4x as …
> Even better category counts

- test/system/volunteer/shifts_test.rb
Skips a system test for viewing the volunteer shift calendar.
I looked into why CI is [failing on main](https://github.com/rubyforgood/circulate/runs/7552874488?check_suite_focus=true) and the failing test seems related to this commit https://github.com/rubyforgood/circulate/commit/bc4583d700bc1c8137bc9fd8b0969aa6af081682, redirecting users to a Teamup link to handle volunteer shifts.
I don't know the plan for the volunteer calendar in the future, so I figured skipping the test for now would at least get the test suite to green and unblock any upcoming work :)
> Skip volunteer shifts calendar test

- app/views/items/show.html.erb
Checkout notices will not be shown on the member side of an item view no matter what.
Fixes #1047
Checkout notices generally have librarian information not relevant to borrowers.
Before: 
After:
Librarian View remains the same:
> Remove checkout notices appearing for members #1047

- db/migrate/20190807020247_add_payment_info_to_adjustments.rb
- db/migrate/20190911020605_add_kind_to_adjustments.rb
- db/migrate/20191102002601_create_notifications.rb
- db/migrate/20200621211015_add_roles_to_users.rb
- db/migrate/20200710004507_create_hold_requests.rb
- db/migrate/20201002020141_add_power_source_to_items.rb
- db/migrate/20201112012007_create_item_attachments.rb
- db/migrate/20210204025839_create_renewal_requests.rb
- db/schema.rb
I think this makes migrations work!
The `activerecord-postgres_enum` gem was updated across a major version bump in https://github.com/chicago-tool-library/circulate/pull/928
The 2.0.0 gem release notes include the change:
> BREAKING Renamed enum_name to enum_type because Rails 7 added basic support for enums
I believe this is necessary for `db:migrate` to work.
The `schema.rb` changes look to be cosmetic reordering _except_ the dropping of this line:
```
enable_extension "pg_stat_statements"
```
It looks like this is never added via a migration. From some history spelunking I see it was:
1. Added in ba23291c7594c429aec32226c54ed8c48514c905
2. Removed explicitly in 6b2e1d2467079609a7324d015e8bed312d7fab86
3. Added back in 8e35c8f46ef63621b051b95f5860f926b308abdb
Do we know if we want this …
> Fix "missing keyword: :enum_type" in migrations

- Dockerfile
This fixes a permissions issue I was experiencing on WSL2 + Docker. It also fixes missing assets by baking them into the image.
Improves on boarding
Assuming docker-compose is being used in a dev environment, there's another service that should be running for webpack with the dev reload enabled. I left this out as we're moving to esbuild anyways. I can implement that service once that PR is merged.
* I have the time and interest to make additional changes to this PR based on feedback.
> Fix permissions issue and missing assets in dockerfile

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/initializers/filter_parameter_logging.rb
* Configures the production logs to log in a single-line format to appsignal
This will make our logs more searchable and also adds a `user_id` property so we can see what actions a given user takes.  A few times now we've needed to understand a bug report from a user and didn't have this as a diagnostic tool.
* Added the `lograge` gem.
* In production, configured logs to go to appsignal using the logfmt format.
* The development logs and normal Rails logs that go to Heroku should remain unchanged.=
> Configure production logs to go to appsignal.

- app/controllers/account/holds_controller.rb
- app/helpers/holds_helper.rb
- app/models/appointment.rb
- app/models/hold.rb
- test/factories/appointments.rb
- test/models/appointment_test.rb
- test/system/remove_holds_test.rb
This PR will merge in the work done by @stephanieminn  in #1067:
- Allows members to remove holds that are associated with an appointment, and ensures that the hold removed from the appointment.
- If the hold was the only item in the appointment, the appointment is canceled.
Resolves https://github.com/rubyforgood/circulate/issues/802 and https://github.com/rubyforgood/circulate/issues/666!
I noticed that `Hold` was defined to have a `has_many` relationship with appointments, but experimenting with the app led me to believe that it shouldn't be possible for a hold to be added to any other appointment. As a result, I did a lil refactor to enforce that a hold `has_one` appointment relationship to make the subsequent work easier.
I also added a `dependent: :destroy` strategy for appointment …
> Revive PR#1067

- .envrc
- .gitignore
- DOCKER.md
- NIX.md
- README.md
- flake.lock
- flake.nix
- test/application_system_test_case.rb
I'm loathe to be the guy who comes in and messes with the development environment as the first thing he does, but here I am being that guy. 😅
I've been pretty into Nix for my development environments for the past couple of years for its ability to lock the full set of dev dependencies in a consistent way across machines and operating systems.
I'll use this setup myself either way, but it's a bit less overhead for me if I'm able to check in the configs vs dancing around local gitignores to keep it working. Plus it gives other people the opportunity to use it!
I tried to document everything nicely, keep it off to the side, and make it minimally invasive. But I totally understand if you'd rather keep this out of the repo! Just let me know. 🙇🏻 
----
Commit message:
> This setup works well for …
> Add Nix development setup

- app/views/renewal/home/index.html.erb
This PR removes the reference to making payments on the renewals home page when payments are disabled by the library.
[Disable online payments using Library setting#1146](https://github.com/chicago-tool-library/circulate/issues/1146)
Before (with payments disabled by the library): 
After (with payments disabled):
After (with payments enabled):
> Don't show references to payments when allow_payments is false

- app/views/member_mailer/membership_reminder.text.erb
- app/views/member_mailer/welcome_message.text.erb
- app/views/signup/confirmations/_instructions.html.erb
- test/controllers/signup/confirmations_controller_test.rb
- test/mailers/member_mailer_test.rb
Resolves #1145 
This could help with email deliverability!
- Caught some duplication in the text version of the welcome email - added a covering test and fixed it.
- Some callers of the `instructions` partial use locals to pass `library` and others use instance variables. I think ideally moving to explicit locals is a bit cleaner, but I decided to continue to handle both in the partial for now rather than taking on the larger task of changing all the callers.
- Added basic unit tests for a couple other member emails which caught a deprecation warning on rendering a partial with a filename suffix.
> Add note about adding library email to contacts to welcome messages

- app/controllers/concerns/lending.rb
- test/controllers/concerns/lending_test.rb
`undo_loan` returns true when loan is successfully destroyed.
Fixes bug where error message is displayed even if loan was successfully undone described [here](https://github.com/chicago-tool-library/circulate/issues/1149)
Old:
New:
> return true when undo_loan is successful

- CONTRIBUTING.md
- README.md
- lefthook.yml
Replaces the contents of the current contributing guide with a shorter and up to date list of steps.
This content is in a Google Doc currently, but we may as well keep it with the code.
* I also updated the `lefthook` config that auto-generates the README table of contents. There has been some churn due to different tooling formatting nested lists with different syntax; hopefully this resolves that.
> Update contributing guide

- NIX.md
- flake.nix
Allows pre-commit linters to run in Nix development environments.
Reduces likelihood of back-and-forth based on formatting issues.
Lefthook needs to be able to invoke `node` directly so explicitly add `nodejs` to dependencies as well. This is probably worthwhile for asset generation stuff anyways.
> nix: add lefthook

- .solargraph.yml
- Gemfile
- Gemfile.lock
The current checked-in configuration runs Solargraph with a default Rubocop config which goes a bit wild with suggestions. This should make the LSP only suggest things that match the rules from Standard Ruby.
Having the LSP config match the linter makes it a bit faster to write complaint code since you'll get suggestions in-line when using an LSP-supporting editor.
> Configure Solargraph with Standard Ruby

- bin/setup
Changes the `bin/setup` script to fail if `yarn` does not work.
This makes `bin/setup` halt with an error message saying to install Yarn before continuing, which should help folks getting started know they need to install that prerequisite.
> require yarn succeed in bin/setup

- .env
- app/helpers/items_helper.rb
- config/application.rb
- test/helpers/items_helper_test.rb
This changes the app to only rely on ActiveStorage and removes the third party dependency on ImageKit.
Modern versions of Rails should be perfectly capable of serving thumbnails directly out of S3 without the help of a 3rd party service.
Resolves #1150 
* This turns ActiveStorage variant tracking on which removes the need for extra checks in S3 for variants. There's no need for an additional DB migration to turn this on as [we already have the tables from the Rails 6.1 upgrade](https://github.com/chicago-tool-library/circulate/blob/remove-imagekit/db/migrate/20210216165140_create_active_storage_variant_records.active_storage.rb).
* Since this change is messing with a dependency I'd recommend immediately testing image views, uploads, and editing after we deploy, which should let us revert …
> Remove ImageKit

- app/controllers/admin/items_controller.rb
- app/controllers/items_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/item_filter_controller.js
- app/models/hold.rb
- app/models/item.rb
- app/views/admin/items/index.html.erb
- app/views/items/_available_now_filter.html.erb
- app/views/items/index.html.erb
- test/models/item_test.rb
- test/system/admin/items_test.rb
- test/system/item_filtering_test.rb
Resolves #1166
Allows item search results on both the public facing and admin tool inventories to be filtered by items "available now," meaning they have no holds or loans and aren't in maintenance.
This is useful for people who want a tool they can pick up immediately.
https://github.com/chicago-tool-library/circulate/assets/37534/d4e7231d-1b60-4167-9341-bef37d99adb1
* I needed to convert the `Hold.active` scope to ActiveRecord so that `Item.active_holds` would be able to chain properly in the `Item.available_now` scope.
* With the plain string version, the queries were failing with "ambiguous column" errors on `ended_at`.
* The unit tests on that query were pretty good (as I learned when I mixed up the `>` and got a million failures 😂) so I'm reasonably confident this is a one-for-one …
> Available now item filtering

- config/appsignal.yml
Resolves #1174
Prevents AppSignal from treating RecordNotFound errors as reportable exceptions.
It's important for us to only alert on real errors or we're more likely to suffer alert fatigue and miss a true problem.
* My first stab at this was reworking `ItemsController#show` to not raise an exception, but my research suggests that letting an exception generate the 404 is a normal setup for Rails. We already have [routes](https://github.com/chicago-tool-library/circulate/blob/ab0a397598cb1d454ea3b495b5d35eab7ad26210/config/routes.rb#L188-L190) and [`exception_app`](https://github.com/chicago-tool-library/circulate/blob/main/config/application.rb#L47-L48) set up to do this.
* I looked into other mechanisms for handling exceptions like …
> Ignore RecordNotFound errors in AppSignal

- flake.nix
Adds the Heroku CLI to the Nix Development environment
Need the Heroku CLI in scope for anybody doing deployments
> nix: add heroku

- app/controllers/admin/reports/items_with_holds_controller.rb
- app/views/admin/reports/items_with_holds/index.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- test/controllers/admin/reports/items_with_holds_controller_test.rb
Adds a new report that lists items with holds and how many holds they each have.
I think this is likely generally useful for folks to know what has the most holds. I wanted it to help keep an eye on the other hold changes that I rolled out as well.
> Add report to list items that have active holds (and how many).

- app/controllers/account/members_controller.rb
- test/controllers/account/members_controller_test.rb
Fixes error seen here https://appsignal.com/chicago-tool-library/sites/60596f9214ad662e17191689/exceptions/incidents/144
Prevents logged out users from seeing an error page if they pull up membership page somehow.
I found `BaseController` in the `account` directory which requires auth for all actions. It seemed like the best fix was to inherit from that.
> Fix error when logged out user views membership page

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/renewal/payments_controller.rb
- app/controllers/signup/payments_controller.rb
- yarn.lock
This PR closes #1160 to Remove the outdated Sentry gem, as well as removes related code causing tests to fail after its removal. Thank you for your patience 
I took a very top-down approach to this ticket, first removing the sentry-raven gem, then running tests and inspecting the related files. I'm very new to the codebase, so I appreciate any extra pairs of eyes to my changes. 
I noticed my `yarn.lock` file had a *lot* of changes to it. Please take a look at that commit. I don't know if it had to do with some of the issues I had in my set up. I'd like to make sure it doesn't cause any problems in the future. Appreciate it!
- [💚] I have the time and interest to make additional changes to this PR based on feedback.
> Remove sentry

- app/views/layouts/application.html.erb
- app/views/layouts/steps.html.erb
We aren't using the Weglot service to translate UI text, but the app still attempts to load it. This removes references to that service from the app.
Fixes [#1199](https://github.com/chicago-tool-library/circulate/issues/1199).
> Remove weglot references. Fixes #1199

- app/controllers/renewal/payments_controller.rb
- test/controllers/renewal/payments_controller_test.rb
Adds a controller test for `Renewals::PaymentsController`, based heavily on the one we have for `Signup::PaymentController`. This is a followup to #1192, which fixed a bug but did not include tests for timing reasons.
This is a critical flow in the application, and we'd like to ensure that it is still working as intended 😄 
* There's a decent amount of duplication between `Renewals::PaymentsController` and `Signup::PaymentController`, and the same is true of their tests. It is looking like we may end up re-working the payment flows as a part of upcoming work, so I opted to not do anything too invasive at this time.
> Add controller tests for renewals/payments

- flake.lock
- test/application_system_test_case.rb
System tests started failing at https://github.com/chicago-tool-library/circulate/actions/runs/7199427363/job/19648174580
This looks to be because selenium-webdriver started fetching Chrome 120 which ran us into this issue: https://github.com/SeleniumHQ/selenium/issues/13112
The recommended workaround there is to change the `--headless` argument in Chrome to `--headless=new` which seems to work locally.
Build's gotta pass!
* The `flake.lock` changes are a result of running `nix flake update` which I did to update to Chrome 120 in the nix dev environment.
> Fix Capybara log fetching in Chrome 120

- app/controllers/admin/appointments_controller.rb
- app/controllers/admin/settings/exports_controller.rb
- app/views/account/appointments/_form.html.erb
- app/views/account/appointments/index.html.erb
- app/views/account/loans/index.html.erb
- lib/tasks/email.rake
Fixes an issue where, after 6pm CST, the appointments page would show incorrect labels for the day. It would show 'Today' for tomorrow and 'Tomorrow' for the day after tomorrow. 
In application_controller.rb, we attempt to manually set the time zone in the around_action to use Chicago time. However, there are a few places where we were using time/day functions that don't take time zone into account. See this article [here](https://thoughtbot.com/blog/its-about-time-zones#a-summary-of-do39s-and-don39ts-with-time-zones) for more info on this. Switching to use suggested functions should resolve the issue and we will apply the correct labels. 
Note: wasn't able to reproduce the exact issue locally, possibly because my local machine is already in Chicago time, but the changes seem low risk …
> Fix appointment titles

- app/assets/stylesheets/styles.scss
- app/views/admin/appointments/_checkins.html.erb
- app/views/admin/appointments/_checkouts.html.erb
- app/views/admin/items/show.html.erb
- test/factories/items.rb
This PR includes checkout notices in the librarian view of the member appointment when an item is checked in or out. I also tried to keep styling consistent across the application and took notice length into account. A `checkout notice` field was added to the item factory for inclusion in testing.
A request from the librarians to be able to see the checkout notices easily when interacting with a customer. Closes issue #678 
From the issue: "These notices contain really important information about items (safety, necessary components etc.) and while they aren't on all items, they need to be seen by librarians before the member takes the item."
A view of before changes were made, this item has a checkout notice, but it is not appearing in the librarian view
Same item, with a checkout notice: …
> Checkout notices/librarian view

- app/models/item.rb
- app/views/admin/items/_form.html.erb
- test/models/item_test.rb
We originally treated A tools (those that we don't individually number) specially, with the idea being that having their numbers be 3 digits would be another signal that they were A tools. This worked, but... we're gonna run out of numbers since B tools start at 1000.
So the solution is to remove that special case for A tools. Once this is merged, all new items will get the next available number in the system.
I don't know what will happen if we hit 1000 for A tools, but let's not find out.
> Remove special case for numbering A tools. Fixes #1223.

- db/devdata/action_text/rich_texts.yml
- db/seeds.rb
- lib/tasks/devdata.rake
This improves a few things about how we do devdata based on a discussion at tonight's meetup:
It's important that we reduce the number of sharp edges in the development environment so that we're as welcoming to new volunteers as we can be.
* We now generate a lot of events, (two a day, three days a week, each week for the next year). This means that folks won't have to run `bin/reset` if it's been more than a week since they last ran it. I still think it's a good idea to run it fairly often, but what we have now is a pretty bad experience considering that contributors are likely to go more than a week while working on a feature.
* Hardcoding an encrypted password should mean that you don't get logged out when you run `bin/reset` anymore!
* I updated the Documents to contain human-friendly …
> Improve devdata somewhat

- app/controllers/admin/appointment_holds_controller.rb
- test/controllers/admin/appointment_holds_controller_test.rb
Fixes #989. Previously, the "Remove Item" button removed the item from the appointment *and* canceled the member's hold on the item. Now the "Remove Item" button works as expected: it removes the item from the current appointment but does not remove the member's hold on the item.
Fixes #989
No UI changes.
* The `cancel_hold` parameter was being passed to the `remove_appointment_hold` method as a string rather than a boolean value, which caused the conditional statement to always evaluate as true. I fixed the issue by coercing to a boolean value, which I think should work whether the parameter is passed in as a string or a boolean. Let me know if it would be better to fix it upstream, i.e., by making sure we're passing a boolean into the function rather than a string.
* I did not create or …
> Fix "remove item" button in appointment

- app/javascript/controllers/application.js
- app/javascript/lib/appsignal.js
- package.json
- yarn.lock
We're using [AppSignal](https://www.appsignal.com) to track server-side exceptions already. This PR sets things up so that we are notified if there are client-side errors in the app's JavaScript.
With the recent move to the latest Turbo, it seemed like a good time to get this in place in case there are any issues in the new front end code.
We want to know if the JS code breaks in anyone's browser.
* This will only track errors that occur within Stimulus controllers. That is probably a good place to start.
* AppSignal recommends **not** catching all client-side errors (which is why their library doesn't by default) due to the amount of noise generated by browser extensions, ad blockers, etc.
* It wouldn't be a bad idea to consider moving our rebuild config into config files as we're …
> Setup Appsignal to track front end errors.

- app/views/devise/mailer/reset_password_instructions.text.erb
- test/mailers/user_mailer_test.rb
Hopefully this addresses the problem in #1245 - we'll need to test deliverability in production to know if it fixes it or not.
We don't want any emails to be marked as spam - especially password reset emails!
* See https://github.com/heartcombo/devise/issues/5034 for some good background on this approach.
> Add text part to password reset emails

- app/views/renewal/payments/new.html.erb
- app/views/signup/payments/new.html.erb
- test/system/membership_renewal_test.rb
- test/system/user_signup_test.rb
The buttons in our payments flows that redirect aren't working properly with the newest version of Turbo. This PR disables Turbo for those buttons and also updates the remote system tests we have that verify this behavior so that they are compatible with the current version of the Square checkout page.
* The two APIs we are using are deprecated, so I'll follow this PR up with another that replaces those with different APIs based on their recommended migration docs.
> Disable turbo on buttons that redirect to Square.

- config/appsignal.yml
We were getting this warning on staging:
```
[2024-01-21T01:30:15 (process) #2][ERROR] appsignal: Not loading from config file: config for 'staging' not found
```
I added a config for `staging` to the appsignal config file so that it goes away and we start sending errors to appsignal. 
> Turn appsignal error collection on in staging environment.

- app/assets/stylesheets/account.scss
- app/views/account/appointments/index.html.erb
- lib/tasks/devdata.rake
Fixes #1236. Readability improvements to the member appointment page. It fixes the points called out in the issue, plus a few other small changes.
* Decrease the font size of the date and time
* Move images to the left of descriptions
* Remove horizontal lines between items
* Add vertical margin between the "Appointments" section and the "How do appointments work" section when viewed on small screens (e.g., phones). There was already a horizontal margin when viewed on a wide screen.
This PR also adds images to all items in the development version of the app. The same image is used for all items.
#1236 
Before:
After:
The main issue was a div tag that wasn't closed properly. That caused the date/time header to flow directly into the card body rather than starting a new line.
_Please choose …
> Improve readability of member appointment page

- .github/workflows/ci.yml
Should address warnings about node in CI
Fixes #1241
Warnings bad, updates good!
> CI: Update actions/checkout to use latest version

- db/schema.rb
- lefthook.yml
- test/controllers/concerns/lending_test.rb
- test/models/loan_test.rb
- test/test_helper.rb
This gets us a fresh dump of the schema by running `db:drop`, `db:create`, and `db:migrate`.
The most important diff here is the `precision: nil` additions, which you can read about at length here:
https://github.com/rails/rails/issues/44571
Because of this change, we can drop the special timestamp handling we had added in the interim upgrades.
Keeping the `schema.rb` consistent helps us reduce odd diffs in future work that modifies the database.
> Get a fresh schema dump post Rails upgrades

- app/controllers/account/appointments_controller.rb
- app/mailers/member_mailer.rb
- app/views/member_mailer/appointment_updated.html.erb
- test/controllers/account/appointments_controller_test.rb
- test/mailers/previews/member_mailer_preview.rb
- Added appointment_updated email template
- Changed single instance of appointment_confirmation to appointment_updated for existing appointment updates in appointment controller
- Updated integration test to expect appointment_updated for existing appointments
[Issue 1220 :)](https://github.com/chicago-tool-library/circulate/issues/1220)
_"When someone edits an appointment, the email that we send makes it sound like a new appointment was scheduled. We should update the email we send to say "an appointment was updated" instead of "new appointment scheduled"."_
* _Any open questions you have about the PR or areas …
> Create appointment updated email

- app/controllers/concerns/lending.rb
- test/controllers/concerns/lending_test.rb
- Change return of create_loan method to always return loan so loans_controller persisted? logic handles items appropriately
- Create test for creating loans for items in maintenance scenario
[Issue 1247](https://github.com/chicago-tool-library/circulate/issues/1247) addresses issue where undefined values were being passed and causing internal server errors.
Close your eyes and imagine a HTTP 500 slowly fading away~
* _Anything notable about the technical approach you took._
No
* _Any open questions you have about the PR or areas where you'd like specific feedback._
I have not yet reproduced the error logged in as an admin or verified_member!! I'm new to the app, so I'm not sure how to create a loan on an item in maintenance because I don't see the button to do it for example on item …
> Issue 1247 create_loan bug

- test/system/remove_holds_test.rb
Closes #1275
The tests seem to be failing because the `click_on "Appointments"` action is not working after the `accept_confirm`. This changes the `click_on` to be more conservative and adds an assertion to make the error message clear when that's the step that's failing. It also adds a short sleep between the `accept_confirm` and the `click_on` which in my testing seemed to address the flakiness of these two tests.
Flaky tests bad. Tests should reliably pass!
I know that adding sleeps to address flaky Capybara tests is generally discouraged, but I feel like I exhausted all our other options in this investigation (barring something more drastic like moving away from javascript popups - I did find [one article suggesting they should be …
> Fix flaky RemoveHoldsTest cases

- Gemfile
- Gemfile.lock
- test/controllers/renewal/payments_controller_test.rb
- test/controllers/signup/payments_controller_test.rb
- test/lib/square_checkout_test.rb
Updates minitest and changes tests to pass in the newer version
Staying on the latest version of our dependencies is good
Minitest's interface changed slightly when they added first class support for kwargs, see https://github.com/minitest/minitest/issues/912
Closes #1269
> Update minitest and fix tests

- app/javascript/application.js
- package.json
- yarn.lock
Removes an unused dependency, as discussed in https://github.com/chicago-tool-library/circulate/pull/1272
Less code makes maintenance easier!
> Remove unused smooth-scroll-into-view package

- bin/dev
I noticed that it's easy to forget to install updated dependencies when you've pulled down new code. This adds extra steps to `bin/dev` to do this for you when you start up the dev server.
From my testing this doesn't add a significant delay to everything starting up, and I think it will save folks time from not having done this for both sets of dependencies. Now that we're keeping them fairly up to date, they will change more often.
* Both `yarn` and `bundle ` are invoked with arguments to not output any text, but there is a "Nothing to migrate!" message that is printed when `yarn installs`. I don't think it's a huge deal; we can fix that in the future.
> Install dependencies when starting bin/dev

- README.md
- test/minitest/tags_plugin.rb
- test/test_helper.rb
In the process of upgrading the Square library, I found myself working with our test tagging a bunch and found it rather lacking. I looked for something off-the-shelf, but [the closest thing I could find](https://github.com/ordinaryzelig/minispec-metadata) only works with minitest-spec (which we aren't using).
The [README changes](https://github.com/chicago-tool-library/circulate/pull/1309/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R181) describe how this works fairly well, but here's a high level summary:
* Tests are tagged by passing a list of symbols after the test name, like `test "the app works", :remote do .... end`.
* We don't run tests tagged with `remote` by default.
* I based the syntax for tags off [how Rspec does …
> Add an improved test tagging system.

- Gemfile
- Gemfile.lock
This was added back when we were using CircleCI (4 years ago in #10). I think it allowed the test results to be parsed by the service in some way. Since we are on Github Actions now, I think this can go.
More dependencies, more problems.
> Remove unused dependency minitest-ci

- app/texters/member_texter.rb
Change overdue notice SMS url to new appointment page. The member page does not allow you schedule a return appointment directly.
We're asking users to schedule an appointment to return their tools, so we should route them to a page where that happens.
New target page of link:
> Change overdue notice SMS link to appointment page

- app/controllers/admin/appointment_detail_completions_controller.rb
- app/views/admin/appointments/_complete.html.erb
- config/routes.rb
- test/controllers/admin/appointment_detail_completions_controller_test.rb
Adding a complete button to the appointment details page. Clicking this button completes the appointment and returns to the appointment list page. If viewing a completed appointment, the button will restore the appointment and leave the user on the appointment details page.
Users have requested a button here to avoid having to go back to the appointment list page before completing the appointment.
Before:
After:
Not 100% sure about the creation of the new controller and partial view approach. If the reviewer could make sure that it is following Ruby on Rails best practices, that would be great!
I have the time and interest to make additional changes to this PR based on feedback.
> 894 add complete button to appointment page

- app/lib/activity_notifier.rb
- app/models/loan_summary.rb
- app/texters/member_texter.rb
- test/lib/activity_notifier_test.rb
- test/test_helpers/twilio_helper.rb
- test/texters/member_texter_test.rb
Adds SMS reminder version of our return reminders, which notify members when they have items due tomorrow.
Hopefully text reminders will help more members return items on time.
Text message:
Notifications report:
> SMS Return Reminders

- app/assets/stylesheets/overrides.scss
- app/assets/stylesheets/styles.scss
- package.json
- yarn.lock
The Spectre CSS Framework had stagnated under its original maintainer and some community members forked it to an org, which looks better maintained. https://github.com/spectre-org
They fixed the sass incompatibilities, so we can drop the sass-migrator workaround.
> Update spectre to point to fork

- .github/workflows/ci.yml
We're getting some warnings because [the use of older versions of Node in actions is deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). This updates a few of the steps to newer versions.
> Update some actions to use newer versions of node.

- app/controllers/account/renewals_controller.rb
- test/controllers/account/renewals_controller_test.rb
Addresses [issue 1312!](https://github.com/chicago-tool-library/circulate/issues/1312)
Makes renewing multiple items more seamless!
Users were being routed back to their account home page instead of back to the renewal page for items that could be renewed without librarian consent (as opposed to renewal requested items that were routing users back to the loans page).
It gives the two types of renewals the same behavior. 
Whether or not they should be ideologically separate is a whole other discussion... :P
_Please choose one …
> Issue 1312 Change loan renewal request routing

- app/assets/stylesheets/partials/_admin_appointments.scss
- app/views/admin/appointments/_appointment.html.erb
- app/views/admin/appointments/index.html.erb
- test/system/admin/appointments_test.rb
Changes the appointments view from a table layout to a list of cards to make it more friendly for mobile users
Current appointment list table is truncated and difficult to read on a mobile device
Before:
After:
Converted the table rows to be individual cards. I would not mind extra scrutiny on application of styles and general organization.
Would like to know if the categories that were added is what the user really wants to see (sort of guessed that was a relevant from [doc](https://docs.google.com/presentation/d/16oKmM-0XEf-AmHAV1dwh7IjohHx4wZgvKe4xpBr8PwI/edit#slide=id.g2b35a3e9cda_0_14)).
> 1290 improve appointments table on mobile devices

- Gemfile
- Gemfile.lock
Updates us to dotenv 3, and moves to using that gem directly instead of `dotenv-rails` which is [no longer necessary](https://github.com/bkeepers/dotenv/pull/468).
This effectively the same as #1378, but moves to using `dotenv` as a direct dependency.
> Update dotenv and use it directly.

- flake.lock
- flake.nix
In the nix development environment, this matches the postgres client version with heroku's version (15.6), which only generates warnings during normal usage but when doing pg:pull and pg:push operations, pg_dump will complain about version mismatches.
> nix: update dependencies for postgres client

- .github/dependabot.yml
Reconfigure dependabot to run weekly instead of daily, and have it batch updates into a few groups.
Dependabot has proven to be moderately noisy when running daily, so I think it's worth trying to see if batching feels easier to manage.
* There are a lot of tools for deciding what gets batched together. As I start I tried splitting out rails and linter updates from others, but it'll be easy to tweak these as we learn more.
* Notably [dependabot cannot batch updates across package ecosystems yet](https://github.com/dependabot/dependabot-core/issues/8126), so rails upgrades will still likely need to be done manually so we sync the npm and ruby packages.
> Tell Dependabot to do updates in weekly batches

- app/models/member.rb
- app/texters/member_texter.rb
- db/seeds.rb
- lib/tasks/devdata.rake
- test/factories/members.rb
- test/lib/activity_notifier_test.rb
- test/models/member_test.rb
- test/tasks/holds_test.rb
- test/test_helper.rb
- test/texters/member_texter_test.rb
Members get an initial welcome message from the system when they have opted into text reminders for the first time and when they update their phone number.
This should help inform users about what number future reminders will come from and also how to opt-out if they didn't mean to get them.
* I noticed all our SMS body strings were ending in a newline, so I fixed that and added tests to verify we don't do it in the future. I believe Twilio was stripping these out but I figure it's safer for us to do so ourselves.
> Send welcome SMS to users who opt into text reminders

- app/lib/activity_notifier.rb
- app/texters/member_texter.rb
- lib/tasks/holds.rake
- test/models/member_test.rb
- test/texters/member_texter_test.rb
Fixes member creation when text reminder feature flag is off.
It's broken now!
> Add missing feature flag guard on welcome text

- app/lib/activity_notifier.rb
- app/models/member.rb
- test/lib/activity_notifier_test.rb
Turns out rescuing from RuntimeError is _not_ what you want to do, since TwilioErrors all descent from StandardError but not RuntimeError. Whoops!
This should prevent any future errors from Twilio from stopping the notification train.
* Note that standardrb wants us to omit the error class entirely when rescuing from StandardError, as the bare `rescue` is equivalent to that.
> Fix error guarding in text message code

- app/controllers/admin/renewal_requests_controller.rb
- app/views/admin/renewal_requests/index.html.erb
- test/system/admin/renewal_requests_test.rb
Updates the admin renewal request page to default to "requested" renewals instead of "all" renewals
The user experience for approving loan renewals was tedious requiring extra clicks and scrolling.
Before:
After (default view):
None
> Updating renewal requests to default to requested

- app/controllers/twilio_controller.rb
- config/environments/production.rb
- config/routes.rb
- test/controllers/twilio_controller_test.rb
Implement a Delivery Status Callback for Twilio per their docs at https://www.twilio.com/docs/messaging/guides/track-outbound-message-status
This makes our Notifications records have more up-to-date statuses so we can tell if a text message was actually delivered or not without having to dig through the Twilio console.
* There's a middleware that performs [webhook signature validation](https://www.twilio.com/docs/usage/webhooks/webhooks-security#validating-signatures-from-twilio) so that random traffic can't hit the webhook.
* This is a basic implementation that doesn't account for messages arriving out of order or being missed. Twilio [recommends for production grade applications](https://www.twilio.com/docs/messaging/guides/outbound-message-logging#recommendations-for-maintaining-messagi …
> Handle Twilio message status callbacks

- .github/workflows/ci.yml
- flake.nix
- package.json
- test/lib/version_consistency_test.rb
As a part of #1185 we need to tell the nodejs buildpack which version of node to deploy. To do this we follow [the heroku docs](https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version) and add to package.json.
Added a few unit tests to help us remember to keep versions consistent in the various config files.
Per #1185 this gets us in line with Heroku's recommendations and quells a big warning in the logs every time we deploy.
> Specify node/yarn version where heroku buildpack will find them

- app/controllers/admin/reports/memberships_controller.rb
- app/views/admin/reports/memberships/index.html.erb
Adds full names to membership report
@tessavierk needs a membership report with full member names, and the membership report only shows preferred / first names
> Add full name to memberships report

- app/javascript/controllers/hold_order_controller.js
Fixes #1435
People using iPhones to browse holds can't click the notified user.
* I can't imagine how we'd set up an automated test for this since it only happens on iPhones, but I manually tested it in an iPhone simulator and it seems to fix the issue.
> Fix hold member links on iPhones

- app/models/loan.rb
- lib/tasks/production.rake
- test/models/member_test.rb
Fixes some issues with the production data scrubbing:
* There were some changes needed to accommodate changes to how ActiveStorage handles variants.
* More instances of personal information are cleared out or deleted.
* Some rough edges in the import process have been addressed so that importing production data is less likely to leak PG extensions, etc. into your local environment.
> Update production data scrubbing tasks to be more thorough.

- app/javascript/lib/request.js
- config/environments/test.rb
- test/application_system_test_case.rb
Fixes #1427
There was a small bug in getting the right token content from the meta tag that tests didn't catch because they have CSRF protection off. Turning on CSRF protection in system tests catches this bug and should hopefully prevent future ones too.
> Fix CSRF error when reordering holds

- app/controllers/volunteer/base_controller.rb
Fixes the `UnsafeRedirectError` we [saw yesterday](https://appsignal.com/chicago-tool-library/sites/60596f9214ad662e17191689/exceptions/incidents/3113/samples/timestamp/2024-04-05T02:38:32Z).
Errors bad!
> Fix broken teamup redirect

- app/texters/base_texter.rb
- app/texters/member_texter.rb
- test/test_helpers/twilio_helper.rb
- test/texters/member_texter_test.rb
Resolves #1446 by using [Twilio's message scheduling feature](https://www.twilio.com/docs/messaging/features/message-scheduling) to defer late text messages to the next morning.
Specifically, if a hold available message would go out after 8pm, we schedule it for 9am the following morning.
See #1446 for details.
* I tested this manually with Twilio credentials to verify the scheduling parameters seem to be working how we expect.
* I decided to only add this behavior to hold available messages for a couple reasons:
1. To limit the complexity of this extra logic to a single message type
2. Scheduled messages are an [extra 1.5 cents per message](https://www.twilio.com/en-us/sms/pricing/us#SMS-features) with the first 1000 per month being free. I think since we control the timing of the other …
> Send late hold available texts the next morning

- config/puma.rb
I noticed that we weren't seeing any Ruby metrics in Heroku, despite having followed the directions a while back to set them up:
I am interested in these metrics to help figure out how to tune the app's concurrency and ideally address the memory errors we've been seeing.
The app was setup according the [the Heroku instructions](https://devcenter.heroku.com/articles/language-runtime-metrics-ruby), but evidently [they are out of date](https://github.com/heroku/barnes/issues/36#issuecomment-765733448) and having an explicit require of `barnes` in `config/puma.rb` loads the library before Rails, causing the Barnes server to not start properly and therefore not report metrics.
> Remove barnes require so that Heroku can track Puma metrics

- lib/tasks/email.rake
- lib/tasks/shared.rake
- lib/tasks/sync.rake
I noticed that logs for tasks run through the Heroku scheduler aren't showing up in AppSignal. [Their docs mention needing to add some code to ensure that logs are send before the process exits](https://docs.appsignal.com/ruby/integrations/rake.html#rake-tasks-and-containers), so I added that to the calendar tasks. If it works, we can add it to the other ones that send emails and the like.
It's nice to keep an eye on if these tasks are running and how many events they are updating.
> Wait for logs to write to appsignal before exiting rake tasks.

- app/controllers/admin/bulk_renewals_controller.rb
- app/models/loan.rb
- app/policies/loan_policy.rb
- app/views/account/loans/index.html.erb
- app/views/admin/members/show.html.erb
- test/controllers/concerns/lending_test.rb
Adds language on the member loans page to indicate explicitly when an item is not renewable.
Resolves #1440
> Add message when renewal is not available for an item

- Gemfile
- Gemfile.lock
- app/controllers/account/holds_controller.rb
- app/controllers/items_controller.rb
- app/models/ahoy/event.rb
- app/models/ahoy/visit.rb
- config/initializers/ahoy.rb
- db/migrate/20240411151214_create_ahoy_visits_and_events.rb
- db/schema.rb
This installs the [`ahoy_matey`](https://github.com/ankane/ahoy) gem for first-party analytics and begins using it to track when members do a search, view an item, and place a hold.
As we aim to improve search in the system (#1240), it will be helpful to see what users are actually searching for and whether they are finding it.
* 🤫 By using a first-party analytics system (i.e. one that stores data in the same database we already use and control) we're not storing or exposing any more user information than we already have via our member information and logs.
* 🏋🏻 It's worth noting that this will put more storage pressure on the database, because it's recording rows for stuff we expect users to do a lot. So we'll want to keep an eye on database growth.
* ♻️ Along those lines, will want to …
> Add Ahoy for tracking and begin recording events for tool search

- app/controllers/admin/pickups/checkins_controller.rb
- app/controllers/admin/pickups/checkouts_controller.rb
- app/lib/spectre_form_builder.rb
- app/models/pickup.rb
- app/models/reservable_item.rb
- app/models/reservation_loan.rb
- app/views/admin/pickups/_date_hold.erb
- app/views/admin/pickups/_status.html.erb
- app/views/admin/pickups/show.html.erb
- config/routes.rb
- db/migrate/20240319044204_add_check_out_times_to_reservation_loans.rb
- db/migrate/20240319050749_add_returned_to_pickup_statuses.rb
- db/schema.rb
Extends our group lending prototype to allow for pickups to be checked out and back in to represent a reservation being picked from the library and then brought back sometime later on.
> Add Pickup checkin/checkout

- config/application.rb
Starting in Rails 6.1, the default value of this setting was changed to `:lax`. Our app predates that default, and the current behavior is less secure than the default.
[The Rails guides have more info](https://edgeguides.rubyonrails.org/configuring.html#config-action-dispatch-cookies-same-site-protection).
You can see [the security warning from GitHub](https://github.com/chicago-tool-library/circulate/security/code-scanning/3) as well.
> Use newer default value for config.action_dispatch.cookies_same_site_protection

- app/views/admin/members/_profile.html.erb
Adds a link to the members page that goes to the notifications report, filtered by that member. It turns out this functionality has been there for a while, but there was just not a convenient link that exposed it.
This obviates the need for #1250.
It's really useful to see what communications we've sent to a given member.
* There's already an index in the database on `notifications.member_id`.
> Add link to filtered notifications report

- app/views/admin/appointments/_appointment.html.erb
- app/views/admin/appointments/_appointment_mobile.html.erb
Updates member name display on admin appointments page
* Desktop: Preferred name w/ full name in tooltip
* Mobile: Preferred name w/ full name in parens (since tooltips on links don't work on mobile as there's no hover)
Staff wants to address people by preferred name, but they sometimes need to differentiate between multiple people with the same name.
Desktop:
Mobile:
> Change name display on appointments

- app/controllers/application_controller.rb
- app/lib/non_session_cookie_store.rb
Implements a change suggested [here](https://blog.alex-miller.co/rails/2017/01/07/rails-authenticity-token-and-mobile-safari.html) and [here](https://github.com/rails/rails/issues/21948#issuecomment-147738473) which should hopefully reduce the number of InvalidAuthenticityToken errors we see.
ActionController::InvalidAuthenticityToken is one of the more common errors we see, and though some of them probably come from random web traffic, there are enough to suggest we have an actual issue.
> Attempt fix for InvalidAuthenticityToken errors

- .github/workflows/ci.yml
We added standard to check our front end code in #1472. This extends our existing CI checks to also run that linter.
> Add standardjs check to CI

- Gemfile.lock
- app/controllers/account/holds_controller.rb
- app/views/account/holds/history.html.erb
- test/system/holds_test.rb
Adds pagination to the accounts hold history page.
This will prevent long page load times for long time users. See #1475. 
I wasn't sure how many holds should be shown on each page, so I just left it as the pagy default. 
The test I added might be considered redundant, but I figured I'd leave it in for now. It technically doesn't test the pagination functionality itself. I'm happy to make it do so, but I decided to hold off after I couldn't find a similar test for the other uses of pagy in the app.
I also left a small change in the Gemfile.lock regarding the installation of Nokogiri on laptops like mine.
> Added pagination to account holds history

- Gemfile.lock
- app/controllers/admin/users_controller.rb
- app/views/admin/users/index.html.erb
- test/factories/users.rb
- test/system/admin/users_test.rb
These changes allow admin users to filter the users index page in the admin interface by role. By default they'll see all users, but they can choose admin only, staff only, or members only.
This should make some admin tasks easier when it comes to users. See #1251 for more. 
With the members only filter active:
With the admin only filter active:
With no filters active (ie all users):
The card didn't specifically mention being able to filter by the member role but I included it anyway. ~~Not sure if pagination or sorting would be helpful here as well.~~ I just went through the pagination card for this page (#1496).
> Added filtering by role to the users index page for admins

- flake.lock
- flake.nix
Pulls dependencies of vips into scope in the Nix development setup.
For those of us using the Nix dev setup (only me 🙃) this makes image processing work locally.
* Switches upstream to `nixpkgs-unstable` because we tend to track pretty closely with upstream dependencies on the Ruby and JS side thanks to dependabot, so it's helpful for the underlying libraries to stay tight with upstream as well.
> Update nix setup to support vips

- app/controllers/admin/users_controller.rb
- app/views/admin/users/index.html.erb
Adds pagination with pagy to the users index page under settings.
Currently this page takes just over 2 seconds to load so this should speed things up significantly. See #1249 for more.
Just as basic a pagy implementation as I could manage. I also worked on #1495 which involves filtering this same page. Once one of these is merged it might take a little work on the other to make sure the filters and pagination don't cause any issues with one another, which I'm happy to take care of. Alternatively, these two could be combined? Depends on how useful one is without the other.
> Added pagination to the admin users index page under settings

- app/views/account/appointments/index.html.erb
Updates language on appointments page to indicate that appointments are encouraged but not required.
Reflects reality! According to our librarians "we love when ppl make appointments but its not required anymore."
> Tweak appointment required language

- .github/workflows/ci.yml
- README.md
- bin/reset
- bin/setup
- db/seeds.rb
- lib/tasks/db.rake
Combines `bin/reset` and `bin/setup` into a single idempotent script. `setup` is the default Rails one, and they were minimally different. This way, it's always the same command to get to a workable baseline.
Fixes #1487.
> Consolidate setup and reset scripts

- config/routes.rb
Fixes https://appsignal.com/chicago-tool-library/sites/60596f9214ad662e17191689/exceptions/incidents/3132
It's a bug! 🐛 
It was updated in https://github.com/chicago-tool-library/circulate/commit/c588831d07486a30e12f2cee37d007b5a6d51573
But then it was accidentally moved back in https://github.com/chicago-tool-library/circulate/commit/16ab700e3ed9a6c01853711bc8689add6dfc2ec2#diff-959bc9abc46a55332bb64d5155a79323afa75a50ec1a2137ddd22d926f62c6c5L82-R99
> Fix loan history link

- app/views/admin/members/_lookup.html.erb
- test/system/admin/check_in_check_out_test.rb
- test/system/admin/holds_test.rb
- test/system/admin/members_test.rb
This allows anyone with staff/admin access to create a hold or a loan for a member that already has an overdue loan. It removes a check that prevented this.
It addresses [#665](https://github.com/chicago-tool-library/circulate/issues/665) by removing a roadblock for staff.
Before this change, staff would see this toast message regarding the overdue loan.
After this change, staff will see the usual item "Lend or Hold Item" form.
I just exposed the form in the HTML and didn't have to change any validations or controller checks.
> Staff can create holds or loans for members even if that member has overdue loans

- app/controllers/signup/base_controller.rb
- config/initializers/lograge.rb
This adds the user_id to lograge during the signup process by falling back to the `user` associated with the controller's `member` (if member is defined).
This addresses [#1546](https://github.com/chicago-tool-library/circulate/issues/1546).
It's small, but you can see the `user_id` is `17` in the picture for the `/signup/documents/agreement` path.
`@member` was being set in the signup controllers so I just added an `attr_reader` for it. I leaned on `try` pretty heavily so controllers that don't implement `member` won't be impacted.
> Log the user id when available during the sign up flow

- app/controllers/admin/loan_summaries_controller.rb
- app/controllers/admin/renewal_requests_controller.rb
Refactors some filtering methods to use `case` statements and constants to so that user input is never technically passed to the `send` method.
Addresses [#1507](https://github.com/chicago-tool-library/circulate/issues/1507). Even if the code was safe before, it's nice to have less noise.
Nothing to see here.
I added an `INDEX_FILTERS` constant so all of the values are grouped in an array but nothing uses it. I've seen other patterns for managing constants and kind of just went with this one, but if there's a preferred way to do this I'm happy to make those changes.
> Prevent codescanning warnings by ensuring methods return constant values and not technically user input

- app/mailers/user_mailer.rb
- test/mailers/user_mailer_test.rb
This creates `Notification`s whenever the Devise mailer is used (`UserMailer`). It uses the set `@subject` when present and falls back to the mail object's subject.
This takes care of [#1542](https://github.com/chicago-tool-library/circulate/issues/1542) (this was a draft issue when I started so I converted it into an issue).
Nothing much to see here.
I used the `@subject` instance variable as the default but fell back to `mail.subject` because the emails that are not overridden lack `@subject`. 
When I was first looking at this I assumed that Devise or Rails just automatically picked up on `@subject` and used that as the email's subject line but that doesn't seem to be the case. The email's actual subject in this case is "Reset password instructions" and `@subject` is only used for the …
> Create Notifications whenever Devise sends an email

- app/controllers/signup/base_controller.rb
- app/controllers/signup/members_controller.rb
- test/controllers/signup/members_controller_test.rb
- test/controllers/signup/payments_controller_test.rb
We had an instance of a member taking longer than 30 minutes to complete the signup steps, and it timed out just as they were paying for their membership. You can see [the sample of this occurrence in AppSignal](https://appsignal.com/chicago-tool-library/sites/60596f9214ad662e17191689/performance/incidents/59/samples/60596f9214ad662e17191689-158228531489123241821718233200?selectedTime=2024-06-12T23%3A05%3A00.000Z&activeFilter=date). This meant that the callback from Square was rejected and their membership payment wasn't recorded correctly in our system. The logic to calculate if the time had passed was also hard to follow as it was previously implemented.
This change gives people 2 hours to get through signup. The original time was chosen arbitrarily, and in hindsight I can't say why it …
> Extend signup timeout to 2 hours from 30 minutes

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- Procfile
- app/jobs/neon_member_job.rb
- app/models/member.rb
- config/application.rb
- config/initializers/acts_as_tenant.rb
- config/initializers/good_job.rb
- config/routes.rb
- db/migrate/20240617233510_create_good_jobs.rb
- db/schema.rb
- lib/tasks/devdata.rake
- test/models/member_test.rb
* Switches job system from [Sucker Punch](https://github.com/brandonhilkert/sucker_punch) to [GoodJob](https://github.com/bensheldon/good_job)
* GoodJob gives us a few implementation benefits over Sucker Punch
- It's Postgres-backed, so in-flight jobs won't be lost on server restart
- It can be configured with an external worker, which will reduce memory pressure on the web dyno
- It includes scheduled job features, which will let us migrate from Heroku Scheduler to jobs defined in code
- It includes a dashboard we can use to debug potential issues with background jobs
* We will now have a persistent worker dyno running in both staging and production, which will add $14/mo ($168/yr) to our hosting costs. Initial discussion amongst the team has concluded this is a worthwhile tradeoff for …
> Switch to GoodJob for background work

- Gemfile.lock
Adds `arm64-darwin-23` to the list of platforms. I think it corresponds to macOS 14.x (which is what is on my laptop).
This line keeps getting added to `Gemfile.lock` whenever I install the dependencies for the app.
> Include arm64-darwin-23 in platforms

- app/views/layouts/application.html.erb
Closes #1581
See linked issue for further discussion
Docs for this feature are here: https://turbo.hotwired.dev/handbook/drive#prefetching-links-on-hover
> Disable Turbo links prefetching

- app/controllers/application_controller.rb
- config/appsignal.yml
1. Configures AppSignal to track the `USER_AGENT` header so we know if the issue affect only certain clients. Mobile Safari is a mentioned a lot in the prior art here, but we don't know if our problems also match that pattern.
2. Handle InvalidAuthenticityToken errors by redirecting folks back to where they came from and asking them to try again. In theory this will help if it turns out that folks are hitting this issue by using a cached page that's lost its session, although I think the work done in #1478 should have fixed that.
I couldn't figure out how to succinctly trigger an `InvalidAuthenticityToken` in a controller test, but this code should only affect folks who have already hit an error anyway.
> More attempts to fix InvalidAuthenticityToken issues

- app/models/concerns/item_statuses.rb
- db/migrate/20240716051930_add_missing_to_item_statuses.rb
- db/schema.rb
Adds missing as an option to item statuses
Takes care of #1554
Just changed the enum and its concern. 🤷‍♂️
> Added "missing" to item statuses

- app/views/items/show.html.erb
- app/views/layouts/application.html.erb
This will make the share preview look a little friendlier when people share links in apps that support Open Graph protocol (facebook, twitter/x, LinkedIn, Slack, Apple Messages, etc)
This helps with #867 
Most of the tools that let you preview this functionality want a URL to scrape the information from which won't really be available until this is deployed to an environment. So for now, here's the tags in the dom:
I actually worked on pretty much the same thing last Friday so I can say that Slack will at least pick up these tags.
I used the [Open Graph protocol site](https://ogp.me/) as a guide and didn't bother adding any platform specific tags for now.
> Added basic open graph meta tags to the item show page

- db/migrate/20240720134319_create_good_job_settings.rb
- db/migrate/20240720134320_create_index_good_jobs_jobs_on_priority_created_at_when_unfinished.rb
- db/migrate/20240720134321_create_good_job_batches.rb
- db/migrate/20240720134322_create_good_job_executions.rb
- db/migrate/20240720134323_create_good_jobs_error_event.rb
- db/migrate/20240720134324_recreate_good_job_cron_indexes_with_conditional.rb
- db/migrate/20240720134325_create_good_job_labels.rb
- db/migrate/20240720134326_create_good_job_labels_index.rb
- db/migrate/20240720134327_remove_good_job_active_id_index.rb
- db/migrate/20240720134328_create_index_good_job_jobs_for_candidate_lookup.rb
- db/migrate/20240720134329_create_good_job_execution_error_backtrace.rb
- db/migrate/20240720134330_create_good_job_process_lock_ids.rb
- db/migrate/20240720134331_create_good_job_process_lock_indexes.rb
- db/migrate/20240720134332_create_good_job_execution_duration.rb
- db/schema.rb
Adds missing GoodJob migrations as I didn't notice that Dependabot took us over the major boundary in #1582.
Fixes job errors we're seeing in production that look like https://github.com/bensheldon/good_job/issues/1404
Generated by pinning good_job to 3.99 and running
```
bin/rails good_job:update
bin/rails db:migrate
```
Follow up tasks to consider: 
* Smoke testing GoodJob in tests (I think we'll get this as a matter of course once we start converting some of our cron tasks over)
* Splitting out major version upgrades to separate dependabot group
> GoodJob 4.0 migrations

- .github/workflows/ci.yml
- DOCKER.md
- Gemfile
- Gemfile.lock
- bin/setup
- flake.nix
- package.json
- test/application_system_test_case.rb
- test/system/admin/holds_test.rb
- test/system/admin/notes_test.rb
- test/system/admin/reservations_test.rb
- test/system/appointments_test.rb
- test/system/membership_renewal_test.rb
- test/system/user_signup_test.rb
- test/test_helpers/stdout_helpers.rb
- yarn.lock
Changes from Selenium to Playwright to run our browser based system tests.
The hope is that this is a smidge more reliable / less flaky.
* This is mostly based on a [recent blog post](https://justin.searls.co/posts/running-rails-system-tests-with-playwright-instead-of-selenium/) that reported a good experience switching.
* There were a few places that Playwright had trouble with ambiguous links - it seems to "see" both the mobile and desktop nav menus. Fixed these with `within` scopes.
* The drag/drop test needed an extra delay to work... it seemed like it didn't drag far enough w/o it. I guess playwright is slower to move the virtual mouse!? 😂 
* I decided to yank out Docker support for system tests for now. There is a [story for setting this back …
> Switch system tests to use playwright

- app/controllers/items_controller.rb
- app/views/items/index.html.erb
- test/system/items_sorting_test.rb
Forces the given sort order on the query and capitalized the sort by buttons. 
Addresses #1425 
Without a query, there is no Relevance sort button:
Relevance:
Date Added:
Number:
Name: 
For the sorting, I just changed `order` to `reorder`. The issue was that PGSearch would add a default order by rank that would take priority ahead of any other ordering applied. `reorder` disregards the previous orders on the query and applies our new one. 
For the Relevancy sort I tried always using `reorder` and adding relevance to the hash of sort orders using this [PGSearch utility](https://github.com/Casecommons/pg_search?tab=readme-ov-file#search-rank-and-chained-scopes) but the rank results were different then what PGSearch applies by default. 
I think there's likely a good way to refactor this …
> Fixes the sort buttons on the items index page when there's a search query

- app/controllers/admin/searches_controller.rb
- app/views/admin/searches/show.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- test/factories/items.rb
- test/system/admin/searches_test.rb
Added toggle to limit admin search results to available items only.
Takes care of #1439
With the toggle off:
With the toggle on:
I reused the partial from the items#index and admin/items#index even though it has some hidden field tags we don't really need in this context.
I also removed searches#create since it just passed through to searches#show anyway. Just had to change the forms to be `get` requests.
> Added toggle to limit admin search results to available items only

- app/controllers/application_controller.rb
- test/controllers/application_controller_test.rb
There is still a bug in the custom CSRF handling code:
```
undefined method `Appsignal' for #<Appsignal::Transaction:0x00007f8f23094ae8 ...>
transaction.Appsignal.set_custom_data(
^^^^^^^^^^
```
I added a test for `ApplicationController#handle_invalid_authenticity_token`. It's worth noting that the block passed to `Appsignal.report_error` in that method isn't executed in the test environment, but I manually hacked things up and validated that at least the exception shown above (nor one like it) is no longer happening.
> Fix undefined method error in CSRF handler

- app/controllers/admin/reports/members_with_overdue_loans_controller.rb
- app/models/loan.rb
- app/models/member.rb
- app/views/admin/reports/members_with_overdue_loans/index.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- test/models/loan_test.rb
- test/system/admin/reports/members_with_overdue_items_test.rb
Adds a report that shows each member with overdue loans.
Takes care of #1593 
Report page:
CSV:
More or less copied the pattern from the memberships report.
> Added a members with overdue loans report

- app/assets/stylesheets/globals.scss
- app/assets/stylesheets/overrides.scss
- app/assets/stylesheets/partials/_admin_appointments.scss
- app/assets/stylesheets/public.scss
- app/assets/stylesheets/styles.scss
This reorders some style rules to prevent deprecation warnings from SASS.
Reduces noise and surfaces any issues with SASS now instead of when it upgrades.
An example warning:
```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
More info: https://sass-lang.com/d/mixed-decls
┌──> app/assets/stylesheets/globals.scss
73 │     letter-spacing: $button-letter-spacing;
│     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
╵
┌──> app/assets/stylesheets/mixins.scss
64 │ ┌     a {
65 │ │         color: white;
66 │ │         text-decoration: none; …
```
> Reorder sass rules to prevent warnings

- config/appsignal.yml
Adds `HTTP_REFERER` to the list of headers we're collecting to help diagnose the `InvalidAuthenticityToken` errors we've been seeing.
> Collect referrer in appsignal

- test/system/admin/questions_test.rb
- test/system/admin/reservations_test.rb
Fixes #1610 
Tests should pass 24x7x365!
* We discussed our approach to timezone handling in our meeting last night and agreed that we should do short-term fixes first, and file an issue for a larger refactor: #1611
* I also noticed some timing issues with `assert_match ... current_path` so switched to `assert_current_path` which includes Capybara's default synchronize/waiting behavior.
* I adjusted one reservation test's setup so no timestamps were on adjacent days to make failures clearer.
> Address system test flakes

- .github/workflows/ci.yml
- docker-compose.yml
Moves postgres to run on a tmpfs ramdisk. This yields a modest improvements in bin/setup and test time locally, and hopefully similar speedups in CI.
Faster tests means less human time waiting!
This means that the development database contents will not persist across reboots for people using Docker. The main instructions have folks installing postgres with homebrew, so it won't affect most people.
> Move development and CI postgres to tmpfs ramdisk

- app/controllers/items_controller.rb
- app/views/items/index.html.erb
- test/controllers/items_controller_test.rb
Add more useful information to the "Search" and "Item Viewed" events logged by ahoy.
Specifically, this PR adds the following information:
* Search
+ "params": any parameters included with the search, such as "sort" and "category" (this will also include "query", which we're already logging, but it's probably not too big a deal to include it here too)
+ "n_results": number of results returned by the query
+ "first_page_results": a list of the ordered item IDs on the first page results
+ I'm not sure whether this will be useful/necessary. **See implementation note below.**
* Item Viewed
+ "referrer_url": add the referrer URL so we can connect Item Viewed events to search queries, or see which other places are leading to item views
The additional information will help us understand how …
> log additional information for search and view events

- app/views/admin/reports/members_with_overdue_loans/index.html.erb
Fixes the Members with Overdue Loans Report, which is currently [broken in production](https://chicagotoollibrary.slack.com/archives/C05U0JSJ6AD/p1722191013493979).
It turns out that we have 48 `Member` records without associated `User` objects:
```sql
SELECT COUNT(members.id)
FROM members
LEFT JOIN users on users.member_id = members.id
WHERE users.id IS NULL;
=> 48
```
This data situation is breaking the Members with Overdue Items report, so this PR makes the template more forgiving. Since there is such a small number of members with this issue, we can go in and fix the database at some point. But I'd like to fix the report ASAP so that staff can start using it.
> Handle members with no associated user.

- app/controllers/account/loans_controller.rb
- app/views/account/loans/index.html.erb
- config/routes.rb
- test/system/account/loans_test.rb
Adds a button and controller action to renew all loans.
Takes care of #1311 
The loans page with the button:
The loans page with the button and the flash message:
Right now the button only appears if any one of the loans can be renewed. 
It didn't seem to make sense to lump the request renewal aspect of some of the loans in with this button, but maybe that could be useful at some point.
> Added a renew all button for loans

- bin/setup
Instead of running `yarn add` for playwright, this just runs `yarn install` in the `bin/setup` script. This way the version of playwright that's listed in the package.json is ultimately installed.
I was running into an issue where running `bin/setup` would change the playwright version from 1.46.0 to 1.45.0 in the package.json. If I cleared those changes it would trip up the capybara/playwright immigration and tell me playwright wasn't actually installed.
I think there's a case to be made to lock playwright to what the ruby implementation considers a compatible version (via `bundle exec ruby -e 'require "playwright"; puts Playwright::COMPATIBLE_PLAYWRIGHT_VERSION'`). Maybe a general dependency update changed the package.json and these got out of sync and we just need to figure out a …
> Swapped the yarn add playwright command with a generic yarn install

- package.json
- yarn.lock
The JS side should match the Ruby driver's compatibility declaration - we got ahead of ourselves thanks to dependabot being eager.
> Match playwright yarn version to ruby

- Gemfile.lock
- app/controllers/account/reservations/submissions_controller.rb
- app/mailers/reservation_mailer.rb
- app/views/reservation_mailer/review_requested.mjml
- app/views/reservation_mailer/review_requested.text.erb
- test/application_system_test_case.rb
- test/mailers/reservation_mailer_test.rb
- test/system/account/reservations_test.rb
Sends email to admins when a member submits a reservation
Closes #1531 
This doesn't send the mailer when an admin requests a reservation through `ReservationsController`, since it doesn't seemed like review is required when a reservation is created this way.
> Send reservation requested emails to all admin users

- app/models/member.rb
- app/models/user.rb
- db/migrate/20240904212517_make_members_belong_to_user.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/devdata.rake
- test/controllers/admin/members_controller_test.rb
- test/controllers/items_controller_test.rb
- test/factories/appointments.rb
- test/factories/members.rb
- test/factories/memberships.rb
- test/factories/users.rb
- test/models/member_test.rb
- test/models/user_test.rb
- test/system/admin/check_in_check_out_test.rb
- test/system/admin/holds_test.rb
- test/system/admin/member_verification_test.rb
- test/system/admin/reports/members_with_overdue_items_test.rb
- test/system/member_checked_out_items_test.rb
With these changes members will belong to users instead of users belonging to members.
Having users belong to members is more of a historical artifact than a real design choice. This keeps things to be more like what people would expect.
I added some SQL to the migration to make sure the current member/user relationships are transferred over. There are probably some other improvements that could be made (like the columns could be non-null if we're sure there's a user for every member or pulling some of the overlap between members and users into a profile, etc), but I focused mainly on inverting the relationship.
> Swap member and user relationship

- app/assets/stylesheets/styles.scss
- app/views/items/index.html.erb
Rearranges some markup and bumps up the item name's font size.
[People were suggesting this change in the recent survey](https://chicagotoollibrary.slack.com/archives/C05RB4B5M1N/p1725532818050629)
This doesn't impact the admin items index since the style changes use a class name that's only on the member view.
> Put the item's name ahead of its number on the member view of the items index

- app/controllers/admin/reports/missing_items_controller.rb
- app/models/item.rb
- app/views/admin/reports/missing_items/index.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- db/seeds.rb
- test/factories/ticket_updates.rb
- test/models/ticket_update_test.rb
- test/system/admin/reports/missing_items_test.rb
Adds a report that lists all of the items with a status of "missing"
Takes care of [#1640](https://github.com/chicago-tool-library/circulate/issues/1640)
More or less a version of the items in maintenance report, so the ticket stuff might not be relevant in the long run (It's my understanding that before the "missing" status was added missing items were marked with tickets labelled "missing", so the ticket stuff might help surface those tickets so they can be closed out).
Also, I corrected a mistake I made with the seeds in another PR where the members weren't actually associated with their users. I can pull that out into a separate PR if we need to (my bad).
> Added a missing items report

- app/controllers/account/reservations_controller.rb
- app/models/answer.rb
- app/models/required_answer.rb
- app/models/reservation.rb
- app/views/account/reservations/_answers.html.erb
- app/views/account/reservations/_form.html.erb
- app/views/account/reservations/show.html.erb
- test/factories/required_answers.rb
- test/models/answer_test.rb
- test/models/required_answer_test.rb
- test/system/account/reservations/questions_test.rb
- test/system/account/reservations_test.rb
- test/system/admin/reservations/questions_test.rb
- test/system/admin/reservations_test.rb
Members now have to answer any questions in the system when making a reservation.
#1520 
The new reservation form with a text and number question:
The new reservation form with errors:
The show reservation page with answered questions
Right now a `nil` value for a `number` field is coerced to a `0` so `number` questions/answers can never really be `blank?`. Not sure if this is nice or annoying but I'm happy to change it up if that's what folks prefer.
I didn't get into editing/updating since we're not likely going to have that as a flow in this part of the app. I thought about removing those actions/routes/views but I figured that'd likely end up happening once other ways of interacting with the reservation are worked out.
In order to make the questions optional for admins but required …
> Member facing reservation questions

- app/controllers/admin/reservations/pending_reservation_items_controller.rb
- app/controllers/concerns/reservation_lending.rb
- app/models/application_record.rb
- app/models/item_pool.rb
- app/views/admin/reservations/_pending_reservation_items.html.erb
- bin/setup
- config/routes.rb
- db/seeds.rb
- lib/tasks/devdata.rake
- test/controllers/concerns/reservation_lending_test.rb
- test/factories/pending_reservation_items.rb
- test/system/admin/reservations_test.rb
* This adds the start of "resolving" `PendingReservationItems`, which means we either delete them or expand the reservations to include them.
* I added some reservations to `bin/setup` to make development easier.
* I also fixed #1676 in the process of the last task.
> Resolve pending reservation items

- app/controllers/account/appointments_controller.rb
- app/models/hold.rb
- app/views/account/appointments/_form.html.erb
- test/models/hold_test.rb
- test/system/appointments_test.rb
Fixes a long-standing issue where members can add items that are in maintenance to their appointments. This resulted from some gaps in logic in the appointment and hold code.
Items in maintenance can't be checked out, and it's a bad experience to allow someone to think they can pick something up when they can't. It also created more work for staff, who have to sort it all out when a member is confused by this.
* Only items that have a `status` of `active` are shown on the appointment editing page.
* The logic on the holds page has been fixed so that it says "you are # 1 in line" instead of "ready for pickup" for items in maintenance.
We don't actually let members place new holds on items in maintenance, and at once point we deleted all holds for items when they entered this state. We …
> Don't allow items that aren't active to be added to appointments.

- app/models/member.rb
- test/controllers/admin/members_controller_test.rb
Fixes an issue that was reported by staff. If a member updates their profile, their email is always marked as unconfirmed. This PR limits this to situations where the email has actually change.
> Only update user unconfirmed email if user exists and email was changed.

- app/assets/stylesheets/admin.scss
- app/assets/stylesheets/overrides.scss
- app/assets/stylesheets/partials/_admin_memberships.scss
- app/assets/stylesheets/partials/_items_index.scss
- app/assets/stylesheets/styles.scss
The spectre.css upgrade in #1686 ended up messing up a bunch of spacing in the app, mostly due to changes to the default styles of `p`, `ul`, and `li` elements. I clicked around and fixed the most glaring visual issues, but I wouldn't be surprised if there are more.
I also ended up fixing #893 in the process.
> Remove unnecessary spacing resulting from specter upgrade

- .gitignore
Ignores any local vscode configuration
Don't want to accidentally pollute someone else's text editor.
Git ignore!
> Ignore local vscode configuration

- app/forms/membership_payment_form.rb
- app/views/signup/payments/new.html.erb
- test/system/user_signup_test.rb
Changes some copy and has the form require a minimum of a $5 online donation
Takes care of the requests in #1682 
New copy:
Attempting to donate $4:
Happy to tweak any formatting or anything else. 
I put a validation in the form for the $5 minimum but if someone tries to get around that I also adjusted the minimum in `MembershipPaymentForm`. This also changes the behavior for renewals which isn't in the card but seems like the kind of thing we'd want changed everywhere.
> Tweak sign up for clarity around payments

- app/lib/certificate/generator.rb
Resolves #1689 by attempting to use the `magick` command instead of `convert`, which will be deprecated in Imagemagick 7. This deprecation warning has started showing up on developer machines, and it's annoying.
For bonus fun, Heroku has an older version of imagemagick from before there was a `magic` command. So I added a fallback for environments where we only have the older command.
> Try to use magick command and fallback to convert.

- app/controllers/admin/reservations/reviews_controller.rb
- app/controllers/admin/reservations/statuses_controller.rb
- app/controllers/admin/reservations_controller.rb
- app/helpers/admin_helper.rb
- app/helpers/reservations_helper.rb
- app/models/reservation_hold.rb
- app/views/admin/reservations/_profile.html.erb
- app/views/admin/reservations/index.html.erb
- app/views/admin/reservations/pickups/_reservation_hold.erb
- app/views/admin/reservations/pickups/show.html.erb
- test/system/admin/reservations_test.rb
* Renames two reservation tabs: `items` becomes `reservation` and `pickup` becomes `items`. I think this will make more sense to staff (it already does to me).
* Rebuilds the Items tab to use a table and be more information-dense. This will help the UI scale, be more scannable, and provide a space for other controls as needed.
* Adds the concept of a "default tab" when viewing reservations in the admin. This is so we can have the more relevant tab already selected when folks go to visit a reservation. Which tab this is will vary over the lifecycle of a reservation. The code here is a start but will need adjustment as we continue to build out functionality.
> Improve UI of reservation items screen

- app/assets/stylesheets/globals.scss
- app/assets/stylesheets/header.scss
- app/assets/stylesheets/overrides.scss
- app/assets/stylesheets/partials/_admin_appointments.scss
- app/assets/stylesheets/spectre-css/_variables.scss
- app/assets/stylesheets/spectre-css/mixins/_shadow.scss
- app/assets/stylesheets/styles.scss
When we updated the Sass to use `@use` instead of `@import` in #1716, some of the built-in framework colors stopped being overridden properly. We were using `@import` to just replace global variables for `$primary-color`, etc, but with `@use` everything is namespaced so that no longer works.
I couldn't figure out a nicer way to do this, so I just moved our customization into the main `spectre-css/_variables` file and commented out what was there originally.
Here are a couple places I noticed odd colors:
And after this PR, things are back to normal:
> Move color overrides into the main spectre variables file.

- app/assets/stylesheets/styles.scss
- app/controllers/admin/reports/members_with_overdue_loans_controller.rb
- app/views/admin/reports/members_with_overdue_loans/index.html.erb
- test/system/admin/reports/members_with_overdue_items_test.rb
This changes the members with overdue items report to:
- always show members with the longest overdue items first 
- have filters by borrow policy
#1635 and #1636
The report with no filters active ("All"):
The report with an active filter:
Maybe there's a better way to get everything out in a single activerecord query (ie without `in`) so I'm open to suggestions but this works pretty well.
> Sort the members with overdue items report by most overdue and add borrow policy filters

- test/system/membership_renewal_test.rb
Fixes a test that fails when you are close to the end of daylight savings time.
> Fix system test that fails on DST boundary.

- app/controllers/account/members_controller.rb
- app/mailers/user_mailer.rb
- app/views/admin/members/_profile.html.erb
- app/views/admin/members/notifications/index.html.erb
- app/views/layouts/application.html.erb
- test/controllers/account/appointments_controller_test.rb
- test/controllers/account/members_controller_test.rb
- test/mailers/user_mailer_test.rb
- test/test_helper.rb
We found a couple issues with the way we handle users resetting their emails. The main changes are:
* Show the new email in the "resend confirmation email" modal to staff
* Tweak the app layout so that the confirmation success flash message is shown to members
* Store the email that a notification is going to instead of the value of `user.email` in `Notification#address`.
> Assorted improvements to user email reset flow.

- app/lib/spectre_form_builder.rb
When we switched to the newer version of Turbo, we missed updating how we were disabling form submit buttons in `SpectreFormBuilder`. This might explain some of the issues we've seen with duplicate items.
> Disable form submit buttons once again

- app/controllers/account/appointments_controller.rb
- app/controllers/account/holds_controller.rb
- app/controllers/admin/items_controller.rb
- app/controllers/admin/members/holds_controller.rb
- app/models/item.rb
- app/views/admin/items/_form.html.erb
- app/views/admin/items/_item_panel.html.erb
- app/views/admin/items/holds/index.html.erb
- app/views/admin/members/holds/_form.html.erb
- app/views/items/show.html.erb
- db/migrate/20241105021006_add_enable_holds_to_items.rb
- db/schema.rb
- test/controllers/account/holds_controller_test.rb
- test/controllers/admin/members/holds_controller_test.rb
- test/models/item_test.rb
- test/system/appointments_test.rb
- test/system/holds_test.rb
Adds a new field to items that allows staff to disable holds as requested in #1714.
There are cases where having an item be placed on hold created more trouble than it's worth.
Toggle in the item edit form:
Showing whether holds are enabled in the item sidebar for staff:
Indicating that holds are disabled on public item pages:
* Holds that already exist when this setting is disabled for an item are hidden in the member-facing UI but remain in the database.
> Allow holds to be disabled for individual items

- config/initializers/lograge.rb
Update our [lograge](https://github.com/roidrage/lograge) configuration in two ways:
1. Disable lograge in development and test environments. I think the default Rails log format is easier to read for a human, and we mostly use log rage in production to be compatible with AppSignal's log parsing.
2. Adjusts the way we add additional properties to the logs so that we only add a `user_id` when there is a value. I think this will fix #1568.
> Tweak lograge config

- app/views/admin/renewal_requests/index.html.erb
Added the renewal count to the renewal requests index page and rearranged a few of the columns.
#1654 
The renewal requests index page on a iPad mini
If this page needs to support a narrower screen size we can combine some of the columns but the iPad mini (768px wide in portrait mode) seems like it would cover most devices. Let me know if not!
> Added renewal count to the renewal requests index page

- app/assets/stylesheets/styles.scss
- app/controllers/admin/base_controller.rb
- app/controllers/admin/bulk_renewals_controller.rb
- app/controllers/admin/loans_controller.rb
- app/controllers/admin/members/hold_loans_controller.rb
- app/controllers/admin/members/holds_controller.rb
- app/controllers/admin/renewals_controller.rb
- app/javascript/application.js
- app/javascript/lib/highlight.js
- app/views/admin/appointments/_checkins.html.erb
- app/views/admin/appointments/_checkouts.html.erb
- app/views/admin/categories/index.html.erb
- app/views/admin/members/holds/history.html.erb
- app/views/admin/members/holds/index.html.erb
- app/views/admin/members/show.html.erb
- app/views/layouts/admin.html.erb
- test/controllers/admin/renewals_controller_test.rb
* Adds a new/better way to highlight areas of the page that are updated. This is mostly useful on screens where there are long lists of items, as they sometimes move around as changes are made. I added a `flash_highlight` helper function to manage this- it's easy to just call it in a controller with an `ActiveRecord` object.
* Enables [morphing for page refreshes](https://jonsully.net/blog/turbo-8-page-refreshes-morphing-explained-at-length/#stay-on-the-rails), which should make some interactions where a user is redirected back to the same page they're already on nicer.
* Cleans up some old styles that weren't being used.
> Add flash_highlight and clean up bits of old highlighting.

- app/views/admin/items/_items.html.erb
- test/system/admin/items_test.rb
Just a very small fix. This bug was preventing the display of category links in the admin items index. We were rendering a link around an empty `name` tag, which meant that the links were effectively invisible. With this fix, they show the category name again.
Before: 
After:
> Use category name when linking to categories.

- Gemfile.lock
- app/controllers/admin/items/tickets_controller.rb
Sorts the maintenance tickets by `status` (ascending) and `updated_at` (descending).
#1744 
Order up!
> Sort tickets  on maintenance ticket list on the admin item's page

- Gemfile.lock
- app/controllers/admin/items/tickets/ticket_updates_controller.rb
- app/controllers/admin/items/tickets_controller.rb
- app/models/ticket.rb
- db/migrate/20241113202700_add_retired_to_ticket_status.rb
- db/schema.rb
- test/controllers/admin/items/tickets_controller_test.rb
Add the retired status to tickets, always change an item's status to be retired when a retired ticket is created or a ticket is updated to retired.
#1745 
Item's ticket page with no tickets:
Item's ticket page after creating a "retired" ticket:
Item's ticket page with an "assess" ticket:
Item's ticket page after updating the "assess" ticket to "retired":
I suppose it's possible for the item update to fail (although I don't see how), but I used `update!` so it should surface if it does.
> Add the retired status to tickets

- app/controllers/admin/items/tickets_controller.rb
- app/helpers/items_helper.rb
- app/views/admin/items/_form.html.erb
- package.json
- test/controllers/admin/items/tickets_controller_test.rb
- test/helpers/items_helper_test.rb
- test/system/admin/items_test.rb
- yarn.lock
Disables the maintenance option on the admin item form and marks items as in maintenance after creating a ticket.
#1743 
Select dropdown for a new item:
Select dropdown when editing an item:
Expanded select dropdown when editing an item:
An item just before creating a ticket:
An item right after creating a ticket:
For now I've set it up to only put items into maintenance when creating a ticket. I could see a case for marking items as available once the ticket is resolved, but I can also imagine reasons we might not want that to happen (maybe another ticket was created afterwards or that issue is resolved because it's lost now or something).
> Disable the maintenance option when creating an item

- lib/tasks/production.rake
I noticed that `bin/rails load_production_data_for_export` was broken due to the change we made a while back to swap `users.member_id` with `members.user_id`. This just updates a couple queries to work with the new schema.
> Fix load_production_data_for_export

- .github/workflows/ci.yml
I got an email about v3 being deprecated and will no longer work starting in January 2025. [The docs about this are here](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/). Our use case is pretty simple, so I think this is the only change that's needed.
> Update to version 4 of upload-artifact

- app/views/admin/items/_item_panel.html.erb
- app/views/admin/items/_items.html.erb
- test/system/admin/items_test.rb
Displays `item.status` on the admin item's index and show pages in addition to the `item_status_label` version.
#1742 
Admin items  index page:
Admin item show page:
Just added the capitalized version of the status to both pages. Right now it's background is always gray, but we could add some colors to make it a little nicer if it's not too noisy.
> Show the raw value of each item's status in addition to the member facing version in the admin interface

- app/controllers/admin/reservations/check_ins_controller.rb
- app/controllers/admin/reservations/reservation_loans_controller.rb
- app/views/admin/reservations/check_ins/_form.html.erb
- app/views/admin/reservations/reservation_loans/_form.html.erb
- app/views/admin/reservations/reservation_loans/_reservation_hold.html.erb
- test/system/admin/reservations/reservations_test.rb
This replaces how we look up reservable items in the group lending code to use the human-friendly item number instead of the database ID.
This fixes #1777.
We're going to import items from an external system, and we want to be able to change the number without messing with data integrity.
> Look up items by number instead of database ID

- app/controllers/admin/reports/monthly_activities_controller.rb
- app/models/monthly_appointment.rb
- app/models/monthly_loan.rb
- app/models/monthly_member.rb
- app/models/monthly_renewal.rb
- app/views/admin/reports/monthly_activities/index.html.erb
- db/migrate/20250105181935_create_monthly_renewals.rb
- db/migrate/20250122225005_update_monthly_loans_to_version_2.rb
- db/schema.rb
- db/views/monthly_loans_v02.sql
- db/views/monthly_renewals_v01.sql
- test/system/admin/reports/monthly_activities_test.rb
This adds a renewals column to the activities report and breaks the report into different tables by year.
#1653
The number of renewals for the month is the number of loans created with an `initial_loan_id` and I changed the `monthly_loans` view to only contain loans without an `initial_loan_id`.
> Added a column for renewals count to the activity report

- app/models/reservable_item.rb
- db/migrate/20250202194446_add_myturn_meta_to_reservable_items.rb
- db/schema.rb
- lib/tasks/myturn_import.rake
Adds a new `jsonb` column to `reservable_items` to store arbitrary key/value metadata from imported items. This gives us a way to persist some data that doesn't map cleanly into our schema for future use. One example is that this gives us a way to capture the image URL for each item that we can later fetch and store properly.
> Capture misc metadata from imported items in a column

- app/models/reservation_hold.rb
- app/models/reservation_loan.rb
- app/views/admin/reservations/reservation_loans/_reservation_hold.html.erb
- db/migrate/20250205054754_modify_reservation_loans_quantity.rb
- db/schema.rb
- test/factories/item_pools.rb
- test/factories/reservation_loans.rb
- test/models/reservation_hold_test.rb
Adds a validation to close a gap in how we were validating `ReservationHolds`. Currently, it's possible to reduce the `quantity` of a `ReservationHold` beneath what's would be required by existing `ReservationLoan` objects. So you could have 4 items added to a reservation, but only 3 "reserved" via `ReservationHold` objects. This breaks the lending model's guarantees, which are based around the `ReservationHold` being the source of truth for item availability.
In the last meetup we had a good chat about other ways to handle this situation, which I think are worth exploring as we iterate on the UI. For now, though, I'd just like to maintain data integrity so we don't end up promising more items than we can actually lend out.
Previously, only some `ReservationLoan` objects had a value for …
> Validate that reservation changes will cover existing loans.

- app/views/admin/settings/exports/index.html.erb
Fixes a bug that was preventing these buttons from working. I think they broken during one of the Turbo upgrades- I think `link_to` with a method doesn't work if Turbo is also disabled for the link.
Since this is an urgent matter, I'm going to merge and deploy this ASAP.
> Change link_to to button_to on exports page.

- app/controllers/admin/appointment_detail_completions_controller.rb
- app/controllers/admin/appointment_detail_pulls_controller.rb
- app/controllers/admin/appointment_pulls_controller.rb
- app/controllers/admin/appointments_controller.rb
- app/javascript/lib/appointments.js
- app/views/admin/appointments/_appointment.html.erb
- app/views/admin/appointments/_appointment_mobile.html.erb
- app/views/admin/appointments/_appointment_orig.html.erb
- app/views/admin/appointments/_complete.html.erb
- app/views/admin/appointments/index.html.erb
- app/views/admin/appointments/index_orig.html.erb
- config/routes.rb
- db/migrate/20250223214915_add_pulled_at_to_appointments.rb
- db/schema.rb
- test/controllers/admin/appointment_detail_completions_controller_test.rb
- test/system/admin/appointments/details_test.rb
- test/system/admin/appointments_test.rb
When looking at the appointments index, admins will now see three groups of appointments: pending, pulled, and completed. They can move appointments between these three states and the page will update accordingly.
They can also make these same changes on the appointment details/show page.
#1848
Mobile version of the appointments index:
Desktop version of the appointments index (the version before the feature flag):
Desktop version of the appointments index (the version after the feature flag):
Show page for a pending appointment:
Show page for a pulled appointment:
Show page for a completed appointment:
I added a `pulled_at` column to the `appointment` since completion as a concept is represented by a `completed_at` column. There is probably some sort of refactoring that could be done …
> Admins can mark appointments as pulled in addition to pending and complete

- app/controllers/items_controller.rb
- app/models/item.rb
This PR makes a small change to search behavior. If two items have the same pg_search score, ties will now be broken by item status (currently, items with the same score are just sorted by item ID). Specifically, the sort order will be available > on hold > checked out > overdue > in maintenance.
This seems like a common sense change. It has minimal impact since it's just breaking ties.
Currently, it's common for overdue/checked out/etc. items to be ranked above available items in search results:
After the change, ties will be broken by item status so available items will be ranked first. (Note that the item status is only being used to break ties for now, so overdue items can still appear at the top of the results if they have a higher pg_search score.)
The logic I used to define the …
> basic search enhancement: break ties with item status

- app/models/appointment.rb
- app/views/layouts/_unpulled_appointments_for_today_banner.html.erb
- app/views/layouts/admin.html.erb
- test/models/appointment_test.rb
- test/system/admin/appointments_notifications_test.rb
Adds a banner to the admin layout that shows how many unpulled appointments there are for today. 
#1849
Just the unpulled appointments notification:
The unpulled appointments notification alongside the renewal requests notification:
Any feedback is appreciated!
> Added an admin layout level notification for today's unpulled appointments

- app/controllers/admin/reports/items_in_maintenance_controller.rb
- app/models/ticket.rb
- app/views/admin/reports/items_in_maintenance/index.html.erb
- Addresses #1804: Adds the ticket tags to the "items in maintenance" report as well as a filter for the tags. This currently allows you to filter on one tag at a time--if we need to filter by multiple tags at once, we'll need to update this! 
Makes tags more helpful!
There is a strange bug where if you refresh the page occasionally, it'll prepopulate old params into the filter fields (it will not filter the results). This is annoying, but I thought it would not come up that often. I think it has to do with the fact that I had to switch to a non-ransack form helper because it was difficult to include the tags in the ransack search (it should be compatible, but it that part of Ransack seems stale--Ransack recently required that you have to allowlist everything you search by explicitly, …
> Show maintenance tags

- app/mailers/user_mailer.rb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/confirmation_instructions.mjml
- app/views/devise/mailer/confirmation_instructions.text.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/email_changed.mjml
- app/views/devise/mailer/email_changed.text.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/password_change.mjml
- app/views/devise/mailer/password_change.text.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/reset_password_instructions.mjml
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.mjml
- app/views/devise/mailer/unlock_instructions.text.erb
- app/views/layouts/mailer.html.mjml
- app/views/layouts/mailer.text.erb
- app/views/member_mailer/appointment_confirmation.html.erb
- test/mailers/previews/user_mailer_preview.rb
This wraps the devise emails (email confirmation/password reset/etc) with the same layout we use for other emails. This has two benefits:
1. These emails now look more official to recipients
2. The emails are less minimal, which might have been a factor is our devise emails being flagged as "suspicious" by gmail.
Here's an example of how devise emails now look:
* I also took this opportunity to setup mailer previews for the devise emails, so we can preview them along with our other emails.
> Wrap user emails in our standard email layout

- app/views/account/_membership_renewal_message.html.erb
- lib/tasks/email.rake
- test/factories/memberships.rb
- test/models/membership_test.rb
- test/system/membership_renewal_test.rb
Fixes a bug where a user would receive their renewal notice email and then visit the site and be unable to see the "Renew Membership" banner (they could click the link in the email but didn't)
#1889 A member ran into this issue the other day
The memberships factory was steamrolling the `ended_at` so I tweaked it to prevent the steamrolling, but that led to me having to tweak the dates in a membership validation test.
> Ensure that if the renewal email has been sent, the renewal banner is also showing in app

- app/lib/member_exporter.rb
- app/models/membership.rb
Adds a new field for each year in the members/membership exported CSV. This can be inferred from the other columns, but having an explicit column and value makes importing into other systems easier.
> Add membership_type field to member/membership exports

- app/controllers/admin/item_pools_controller.rb
- app/controllers/admin/reservations_controller.rb
- app/lib/spectre_form_builder.rb
- app/models/item_pool.rb
- app/models/reservation_hold.rb
- app/views/admin/item_pools/_form.html.erb
- app/views/admin/item_pools/_item_pool_panel.html.erb
- db/migrate/20250404163403_add_max_reservable_percent_to_item_pools.rb
- db/schema.rb
- test/models/item_pool_test.rb
Fixes #1530 by allowing staff to set a percentage limit on how much of a given item pool can be claimed by a single reservation.
We don't want a single reservation to use the entire inventory of a given item type.
There is a new field on the ItemPool edit form to set this value:
When set, this limit is shown on the ItemPool show page
Here's an example of the validation working to limit how many items can be reserved:
* I thought about storing a number of items as an integer instead of a percentage as specified in the ticket, but decided ultimately that a percentage is better since it will automatically scale with the number of items (so if we get more items, we don't have to go in and adjust it). I think that's a feature, but it's worth confirming this with staff.
> Add optional limit to how much of an item pool can be reserved by a single reservation

- lib/tasks/devdata.rake
Fixes more things up in devdata.rake similar to #1906. I must've gotten lucky running bin/setup when testing that PR.
Quality of life for everyone
Just spreading that scope around.
> Prevent borrow policy approval errors in devdata rake task

- app/assets/stylesheets/admin.scss
- app/controllers/admin/items_controller.rb
- app/javascript/controllers/confirm_item_accessories_controller.js
- app/javascript/controllers/index.js
- app/models/item.rb
- app/views/admin/appointments/_checkins.html.erb
- app/views/admin/appointments/_checkouts.html.erb
- app/views/admin/items/_form.html.erb
- app/views/admin/items/_item_panel.html.erb
- app/views/admin/loans/_form.html.erb
- app/views/admin/members/show.html.erb
- db/migrate/20250410163403_add_accessories_to_items.rb
- db/schema.rb
- test/factories/items.rb
- test/models/item_test.rb
- test/system/admin/appointments/details_test.rb
- test/system/admin/items_test.rb
- test/system/admin/members_test.rb
Allows librarians to add/edit/remove accessories from items and requires librarians to check off those accessories when lending or accepting a return.
#1851 Helpful reminders for multipart items.
Editing an item's accessories:
Librarian viewing an item's accessories:
Checking out an item when none of the accessories are checked:
Checking out an item when some of the accessories are checked:
Checking out an item when all of the accessories are checked:
After checking out an item with accessories:
Returning an item when the accessories are not checked:
Returning an item when the accessories are checked:
After returning an item:
I added the functionality when checking in/out items through an appointment, but the original issue says to add this to the lending UI and the appointment page. Am I …
> Track item accessories

- app/views/admin/members/_member_details.html.erb
- test/system/admin/borrow_policies_test.rb
Adds all of a member's borrow policy approvals and their current status to the admin member's show page and links to the approval edit page.
#1893 Makes borrow policy approvals (aka "C" tools) much easier for librarians to administrate.
For now I just put them in the side panel but maybe they would be better in one of the tabs on that page. I wanted to hold off on that because it seems like a bigger push and I think we want to surface these to start with. Maybe if we add something like changing their statuses from the member page it'd make more sense to put them behind a tab.
> Link to borrow policy approvals on the member show page

- db/migrate/20250430195751_drop_item_description.rb
- db/schema.rb
It removes the `description` column from `Item` since we use a rich text description for it instead.
#1857 Kind of confusing to use `item.description` and to not be sure if you're getting the column or the rich text.
Tried to keep it easy-breezy.
> Drop the description column from the items table

- app/controllers/admin/documents_controller.rb
- app/controllers/renewal/acceptances_controller.rb
- app/controllers/renewal/base_controller.rb
- app/controllers/renewal/documents_controller.rb
- app/controllers/signup/acceptances_controller.rb
- app/controllers/signup/base_controller.rb
- app/controllers/signup/documents_controller.rb
- app/models/document.rb
- test/factories/documents.rb
Replaces some existing logic around the `code` field to use the Rails `enum` helper. This gives extra functionality in terms of scopes and value checkers.
Rather than needing individual methods added for each Document `code` type, `enum` will give us the methods for free.
n/a
This is not a requested feature, but was something I encountered working on https://github.com/chicago-tool-library/circulate/issues/874 and so thought I would raise for review.
> Refactor Document model to use 'enum' for 'code'

- app/controllers/account/members_controller.rb
- app/views/account/members/agreement.html.erb
- app/views/account/members/borrow_policy.html.erb
- app/views/account/members/code_of_conduct.html.erb
- app/views/layouts/_header.html.erb
- config/routes.rb
Resolves #874: feat: Add ability for a member to view the most recent Document `'agreement'`, `'code_of_conduct'`, and `'borrow_policy'`.
There is currently no way for members to view the policies they agree to when they sign up for a membership.
There is no way to tie a particular Document to a Member agreeing, so we're unable to provide a member with when they agreed to a particular document (or a version of a document) for now, but that would be a good enhancement in the future.
The view/controller method are very similar currently, but opted to leave them distinct so that iteration on each version can be done without affecting other versions.
> Add ability for member to view Documents agreed to

- app/controllers/account/borrow_policy_approvals_controller.rb
- app/controllers/account/members_controller.rb
- app/views/account/members/show.html.erb
- test/controllers/account/borrow_policy_approvals_controller_test.rb
- test/system/member_profile_test.rb
Adds the approval statuses for all borrow policies that require approval to the member's profile page and provides a button for them to request approval if they haven't previously.
#1984 
When no approval request exists:
Requested:
Revoked:
Rejected:
Approved:
I accidentally committed and pushed this straight to `main`, reverted that, and now this is reverting the revert commit 😅 
I removed a couple of assertions around where requesting approval redirects to since now it will just redirect to the referrer (or root if there is not referrer).
> Added borrow policy approval statuses to the member profile page and added the ability to request approval
